kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  namespace: local-tools
  name: citizen-portal
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: dispute-api
  namespace: local-tools
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: postgres
  namespace: local-tools
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: rabbitmq
  namespace: local-tools
