version: "2"
checks:
  method-lines:
    config:
      threshold: 30
engines:
  # ... CONFIG CONTENT ...
  markdownlint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      MD013:
        enabled: false
# ... CONFIG CONTENT ...
plugins:
  tslint:
    enabled: true
  markdownlint:
    enabled: true
  csslint:
    enabled: true
exclude_patterns:
  # Backend File Specific Excludes

  # Frontend Pattern Excludes
  - "src/frontend/citizen-portal/karma.conf.js"
  - "src/frontend/citizen-portal/package.json"
  - "src/frontend/citizen-portal/package-lock.json"
  - "src/frontend/citizen-portal/tsconfig.json"
  - "src/frontend/citizen-portal/tslint.json"
  - "src/frontend/citizen-portal/*.spec.*"
  - "src/frontend/citizen-portal/shared/components/"
  - "src/frontend/*/src/*.spec.ts"
  - "src/frontend/*/src/*.component.ts"
  - "src/frontend/*/src/*/*.component.ts"