apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: splunk
  name: splunk
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: splunk/splunk:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
