apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
  name: citizen-api
  labels:
    app: citizen-api
    app.kubernetes.io/name: citizen-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: citizen-api
    app.kubernetes.io/part-of: traffic-court
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    name: citizen-api
  sessionAffinity: None
  type: ClusterIP
