apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: traffic-court

resources:
  - citizen-api-service.yaml
  - citizen-api-route.yaml
  - citizen-api-deployment-config.yaml
