/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Count { 
    number?: number;
    ticketedAmount?: number;
    amountDue?: number;
    discountAmount?: number | null;
    readonly isAct?: boolean;
    readonly isRegulation?: boolean;
    act?: string | null;
    section?: string | null;
    subsection?: string | null;
    paragraph?: string | null;
    subparagraph?: string | null;
    description?: string | null;
    formNumber?: string | null;
}

