/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeStatus = 'NEW' | 'PROCESSING' | 'REJECTED' | 'CANCELLED';

export const DisputeStatus = {
    New: 'NEW' as DisputeStatus,
    Processing: 'PROCESSING' as DisputeStatus,
    Rejected: 'REJECTED' as DisputeStatus,
    Cancelled: 'CANCELLED' as DisputeStatus
};

