/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DisputeListItemStatus = {
    Unknown: 'UNKNOWN',
    New: 'NEW',
    Validated: 'VALIDATED',
    Processing: 'PROCESSING',
    Rejected: 'REJECTED',
    Cancelled: 'CANCELLED',
    Concluded: 'CONCLUDED'
} as const;
export type DisputeListItemStatus = typeof DisputeListItemStatus[keyof typeof DisputeListItemStatus];

