/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TicketCount } from './ticketCount.model';


export interface Dispute { 
    id?: number;
    ticketNumber?: string | null;
    courtLocation?: string | null;
    violationDate?: string;
    disputantSurname?: string | null;
    givenNames?: string | null;
    streetAddress?: string | null;
    province?: string | null;
    postalCode?: string | null;
    homePhone?: string | null;
    driversLicense?: string | null;
    driversLicenseProvince?: string | null;
    workPhone?: string | null;
    dateOfBirth?: string;
    enforcementOrganization?: string | null;
    serviceDate?: string;
    ticketCounts?: Array<TicketCount> | null;
    lawyerRepresentation?: boolean;
    interpreterLanguage?: string | null;
    witnessIntent?: boolean;
    additionalProperties?: { [key: string]: any; } | null;
}

