/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DisputeSignatoryType = {
    U: 'U',
    D: 'D',
    A: 'A'
} as const;
export type DisputeSignatoryType = typeof DisputeSignatoryType[keyof typeof DisputeSignatoryType];

