/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DisputantUpdateRequestStatus2 } from './disputantUpdateRequestStatus2.model';
import { DisputantUpdateRequestUpdateType } from './disputantUpdateRequestUpdateType.model';


export interface DisputantUpdateRequest { 
    createdBy?: string | null;
    createdTs?: string;
    modifiedBy?: string | null;
    modifiedTs?: string | null;
    disputantUpdateRequestId?: number;
    disputeId?: number;
    status: DisputantUpdateRequestStatus2;
    updateType: DisputantUpdateRequestUpdateType;
    updateJson: string;
    additionalProperties?: { [key: string]: any; } | null;
}

