/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DisputeUpdateRequestUpdateType = {
    Unknown: 'UNKNOWN',
    DisputantAddress: 'DISPUTANT_ADDRESS',
    DisputantPhone: 'DISPUTANT_PHONE',
    DisputantName: 'DISPUTANT_NAME',
    Count: 'COUNT',
    DisputantEmail: 'DISPUTANT_EMAIL',
    DisputantDocument: 'DISPUTANT_DOCUMENT',
    CourtOptions: 'COURT_OPTIONS'
} as const;
export type DisputeUpdateRequestUpdateType = typeof DisputeUpdateRequestUpdateType[keyof typeof DisputeUpdateRequestUpdateType];

