/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DisputeListItemDisputantDetectedOcrIssues } from './disputeListItemDisputantDetectedOcrIssues.model';
import { DisputeListItemSystemDetectedOcrIssues } from './disputeListItemSystemDetectedOcrIssues.model';
import { DisputeListItemStatus } from './disputeListItemStatus.model';
import { DisputeListItemRequestCourtAppearanceYn } from './disputeListItemRequestCourtAppearanceYn.model';


export interface DisputeListItem { 
    createdBy?: string | null;
    createdTs?: string;
    modifiedBy?: string | null;
    modifiedTs?: string | null;
    disputeId?: number;
    ticketNumber?: string | null;
    submittedTs?: string | null;
    disputantSurname?: string | null;
    disputantGivenName1?: string | null;
    disputantGivenName2?: string | null;
    disputantGivenName3?: string | null;
    status?: DisputeListItemStatus;
    emailAddress?: string | null;
    emailAddressVerified?: boolean;
    filingDate?: string | null;
    requestCourtAppearanceYn?: DisputeListItemRequestCourtAppearanceYn;
    userAssignedTo?: string | null;
    userAssignedTs?: string | null;
    disputantDetectedOcrIssues?: DisputeListItemDisputantDetectedOcrIssues;
    systemDetectedOcrIssues?: DisputeListItemSystemDetectedOcrIssues;
    additionalProperties?: { [key: string]: any; } | null;
}

