/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DisputeStatus } from './disputeStatus.model';
import { DisputedCount } from './disputedCount.model';
import { ViolationTicket } from './violationTicket.model';
import { LegalRepresentation } from './legalRepresentation.model';


export interface Dispute { 
    createdBy?: string | null;
    createdTs?: string;
    modifiedBy?: string | null;
    modifiedTs?: string;
    id?: number;
    status?: DisputeStatus;
    ticketNumber?: string | null;
    provincialCourtHearingLocation?: string | null;
    issuedDate?: string;
    submittedDate?: string | null;
    surname?: string | null;
    givenNames?: string | null;
    birthdate?: string;
    driversLicenceNumber?: string | null;
    driversLicenceProvince?: string | null;
    address?: string | null;
    city?: string | null;
    province?: string | null;
    postalCode?: string | null;
    homePhoneNumber?: string | null;
    workPhoneNumber?: string | null;
    emailAddress?: string | null;
    filingDate?: string | null;
    disputedCounts?: Array<DisputedCount> | null;
    representedByLawyer?: boolean;
    legalRepresentation?: LegalRepresentation;
    interpreterLanguage?: string | null;
    numberOfWitness?: number | null;
    fineReductionReason?: string | null;
    timeToPayReason?: string | null;
    rejectedReason?: string | null;
    disputantDetectedOcrIssues?: boolean;
    disputantOcrIssuesDescription?: string | null;
    systemDetectedOcrIssues?: boolean;
    jjAssigned?: string | null;
    ocrViolationTicket?: string | null;
    assignedTo?: string | null;
    assignedTs?: string | null;
    violationTicket?: ViolationTicket;
    additionalProperties?: { [key: string]: any; } | null;
}

