/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeUpdateRequestUpdateType = 'UNKNOWN' | 'DISPUTANT_ADDRESS' | 'DISPUTANT_PHONE' | 'DISPUTANT_NAME' | 'COUNT' | 'DISPUTANT_EMAIL' | 'DISPUTANT_DOCUMENT' | 'COURT_OPTIONS';

export const DisputeUpdateRequestUpdateType = {
    Unknown: 'UNKNOWN' as DisputeUpdateRequestUpdateType,
    DisputantAddress: 'DISPUTANT_ADDRESS' as DisputeUpdateRequestUpdateType,
    DisputantPhone: 'DISPUTANT_PHONE' as DisputeUpdateRequestUpdateType,
    DisputantName: 'DISPUTANT_NAME' as DisputeUpdateRequestUpdateType,
    Count: 'COUNT' as DisputeUpdateRequestUpdateType,
    DisputantEmail: 'DISPUTANT_EMAIL' as DisputeUpdateRequestUpdateType,
    DisputantDocument: 'DISPUTANT_DOCUMENT' as DisputeUpdateRequestUpdateType,
    CourtOptions: 'COURT_OPTIONS' as DisputeUpdateRequestUpdateType
};

