/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeRequestCourtAppearanceYn = 'UNKNOWN' | 'Y' | 'N';

export const DisputeRequestCourtAppearanceYn = {
    Unknown: 'UNKNOWN' as DisputeRequestCourtAppearanceYn,
    Y: 'Y' as DisputeRequestCourtAppearanceYn,
    N: 'N' as DisputeRequestCourtAppearanceYn
};

