/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeListItemJjDisputeStatus = 'UNKNOWN' | 'NEW' | 'IN_PROGRESS' | 'DATA_UPDATE' | 'CONFIRMED' | 'REQUIRE_COURT_HEARING' | 'REQUIRE_MORE_INFO' | 'ACCEPTED' | 'REVIEW' | 'CONCLUDED' | 'CANCELLED' | 'HEARING_SCHEDULED';

export const DisputeListItemJjDisputeStatus = {
    Unknown: 'UNKNOWN' as DisputeListItemJjDisputeStatus,
    New: 'NEW' as DisputeListItemJjDisputeStatus,
    InProgress: 'IN_PROGRESS' as DisputeListItemJjDisputeStatus,
    DataUpdate: 'DATA_UPDATE' as DisputeListItemJjDisputeStatus,
    Confirmed: 'CONFIRMED' as DisputeListItemJjDisputeStatus,
    RequireCourtHearing: 'REQUIRE_COURT_HEARING' as DisputeListItemJjDisputeStatus,
    RequireMoreInfo: 'REQUIRE_MORE_INFO' as DisputeListItemJjDisputeStatus,
    Accepted: 'ACCEPTED' as DisputeListItemJjDisputeStatus,
    Review: 'REVIEW' as DisputeListItemJjDisputeStatus,
    Concluded: 'CONCLUDED' as DisputeListItemJjDisputeStatus,
    Cancelled: 'CANCELLED' as DisputeListItemJjDisputeStatus,
    HearingScheduled: 'HEARING_SCHEDULED' as DisputeListItemJjDisputeStatus
};

