/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DocumentType = 'UNKNOWN' | 'NOTICE_OF_DISPUTE' | 'TICKET_IMAGE';

export const DocumentType = {
    Unknown: 'UNKNOWN' as DocumentType,
    NoticeOfDispute: 'NOTICE_OF_DISPUTE' as DocumentType,
    TicketImage: 'TICKET_IMAGE' as DocumentType
};

