/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DocumentSource = 'Citizen' | 'Staff';

export const DocumentSource = {
    Citizen: 'Citizen' as DocumentSource,
    Staff: 'Staff' as DocumentSource
};

