/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DocumentStatus = {
    Filed: 'Filed',
    Pending: 'Pending',
    Resolved: 'Resolved'
} as const;
export type DocumentStatus = typeof DocumentStatus[keyof typeof DocumentStatus];

