/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmailHistorySuccessfullySent } from './emailHistorySuccessfullySent.model';


export interface EmailHistory { 
    createdBy?: string | null;
    createdTs?: string;
    modifiedBy?: string | null;
    modifiedTs?: string | null;
    emailHistoryId?: number;
    emailSentTs?: string;
    fromEmailAddress?: string | null;
    toEmailAddress?: string | null;
    ccEmailAddress?: string | null;
    bccEmailAddress?: string | null;
    subject?: string | null;
    htmlContent?: string | null;
    plainTextContent?: string | null;
    successfullySent?: EmailHistorySuccessfullySent;
    occamDisputeId?: number;
    additionalProperties?: { [key: string]: any | null; } | null;
}
export namespace EmailHistory {
}


