/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FederatedIdentityRepresentation { 
    identityProvider?: string | null;
    userId?: string | null;
    userName?: string | null;
    additionalProperties?: { [key: string]: any; } | null;
}

