/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileMetadata { 
    fileId?: string | null;
    fileName?: string | null;
    noticeOfDisputeGuid?: string | null;
    documentType?: string | null;
    virusScanStatus?: string | null;
    documentStatus?: string | null;
    ticketNumber?: string | null;
    disputeId?: number | null;
    pendingFileStream?: string | null;
    deleteRequested?: boolean | null;
}

