/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FileHistoryAuditLogEntryType = {
    Unknown: 'UNKNOWN',
    Arfl: 'ARFL',
    Cain: 'CAIN',
    Cawt: 'CAWT',
    Ccan: 'CCAN',
    Ccon: 'CCON',
    Ccwr: 'CCWR',
    Cleg: 'CLEG',
    Cuem: 'CUEM',
    Cuev: 'CUEV',
    Cuin: 'CUIN',
    Culg: 'CULG',
    Cupd: 'CUPD',
    Cuwr: 'CUWR',
    Cuwt: 'CUWT',
    Dura: 'DURA',
    Durr: 'DURR',
    Emca: 'EMCA',
    Emcf: 'EMCF',
    Emcr: 'EMCR',
    Emdc: 'EMDC',
    Emfd: 'EMFD',
    Empr: 'EMPR',
    Emrj: 'EMRJ',
    Emrv: 'EMRV',
    Emst: 'EMST',
    Emup: 'EMUP',
    Emvf: 'EMVF',
    Esur: 'ESUR',
    Fdld: 'FDLD',
    Fdls: 'FDLS',
    Fupd: 'FUPD',
    Fups: 'FUPS',
    Frmk: 'FRMK',
    Init: 'INIT',
    Jasg: 'JASG',
    Jcnf: 'JCNF',
    Jdiv: 'JDIV',
    Jprg: 'JPRG',
    Ocnt: 'OCNT',
    Rcld: 'RCLD',
    Recn: 'RECN',
    Sadm: 'SADM',
    Scan: 'SCAN',
    Sprc: 'SPRC',
    Srej: 'SREJ',
    Sub: 'SUB',
    Supl: 'SUPL',
    Sval: 'SVAL',
    Ursr: 'URSR',
    Vrev: 'VREV',
    Vsub: 'VSUB'
} as const;
export type FileHistoryAuditLogEntryType = typeof FileHistoryAuditLogEntryType[keyof typeof FileHistoryAuditLogEntryType];

