/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileHistoryAuditLogEntryType = 'UNKNOWN' | 'ARFL' | 'CAIN' | 'CAWT' | 'CCAN' | 'CCON' | 'CCWR' | 'CLEG' | 'CUEM' | 'CUEV' | 'CUIN' | 'CULG' | 'CUPD' | 'CUWR' | 'CUWT' | 'DURA' | 'DURR' | 'EMCA' | 'EMCF' | 'EMCR' | 'EMDC' | 'EMFD' | 'EMPR' | 'EMRJ' | 'EMRV' | 'EMST' | 'EMUP' | 'EMVF' | 'ESUR' | 'FDLD' | 'FDLS' | 'FUPD' | 'FUPS' | 'FRMK' | 'INIT' | 'JASG' | 'JCNF' | 'JDIV' | 'JPRG' | 'OCNT' | 'RCLD' | 'RECN' | 'SADM' | 'SCAN' | 'SPRC' | 'SREJ' | 'SUB' | 'SUPL' | 'SVAL' | 'URSR' | 'VREV' | 'VSUB';

export const FileHistoryAuditLogEntryType = {
    Unknown: 'UNKNOWN' as FileHistoryAuditLogEntryType,
    Arfl: 'ARFL' as FileHistoryAuditLogEntryType,
    Cain: 'CAIN' as FileHistoryAuditLogEntryType,
    Cawt: 'CAWT' as FileHistoryAuditLogEntryType,
    Ccan: 'CCAN' as FileHistoryAuditLogEntryType,
    Ccon: 'CCON' as FileHistoryAuditLogEntryType,
    Ccwr: 'CCWR' as FileHistoryAuditLogEntryType,
    Cleg: 'CLEG' as FileHistoryAuditLogEntryType,
    Cuem: 'CUEM' as FileHistoryAuditLogEntryType,
    Cuev: 'CUEV' as FileHistoryAuditLogEntryType,
    Cuin: 'CUIN' as FileHistoryAuditLogEntryType,
    Culg: 'CULG' as FileHistoryAuditLogEntryType,
    Cupd: 'CUPD' as FileHistoryAuditLogEntryType,
    Cuwr: 'CUWR' as FileHistoryAuditLogEntryType,
    Cuwt: 'CUWT' as FileHistoryAuditLogEntryType,
    Dura: 'DURA' as FileHistoryAuditLogEntryType,
    Durr: 'DURR' as FileHistoryAuditLogEntryType,
    Emca: 'EMCA' as FileHistoryAuditLogEntryType,
    Emcf: 'EMCF' as FileHistoryAuditLogEntryType,
    Emcr: 'EMCR' as FileHistoryAuditLogEntryType,
    Emdc: 'EMDC' as FileHistoryAuditLogEntryType,
    Emfd: 'EMFD' as FileHistoryAuditLogEntryType,
    Empr: 'EMPR' as FileHistoryAuditLogEntryType,
    Emrj: 'EMRJ' as FileHistoryAuditLogEntryType,
    Emrv: 'EMRV' as FileHistoryAuditLogEntryType,
    Emst: 'EMST' as FileHistoryAuditLogEntryType,
    Emup: 'EMUP' as FileHistoryAuditLogEntryType,
    Emvf: 'EMVF' as FileHistoryAuditLogEntryType,
    Esur: 'ESUR' as FileHistoryAuditLogEntryType,
    Fdld: 'FDLD' as FileHistoryAuditLogEntryType,
    Fdls: 'FDLS' as FileHistoryAuditLogEntryType,
    Fupd: 'FUPD' as FileHistoryAuditLogEntryType,
    Fups: 'FUPS' as FileHistoryAuditLogEntryType,
    Frmk: 'FRMK' as FileHistoryAuditLogEntryType,
    Init: 'INIT' as FileHistoryAuditLogEntryType,
    Jasg: 'JASG' as FileHistoryAuditLogEntryType,
    Jcnf: 'JCNF' as FileHistoryAuditLogEntryType,
    Jdiv: 'JDIV' as FileHistoryAuditLogEntryType,
    Jprg: 'JPRG' as FileHistoryAuditLogEntryType,
    Ocnt: 'OCNT' as FileHistoryAuditLogEntryType,
    Rcld: 'RCLD' as FileHistoryAuditLogEntryType,
    Recn: 'RECN' as FileHistoryAuditLogEntryType,
    Sadm: 'SADM' as FileHistoryAuditLogEntryType,
    Scan: 'SCAN' as FileHistoryAuditLogEntryType,
    Sprc: 'SPRC' as FileHistoryAuditLogEntryType,
    Srej: 'SREJ' as FileHistoryAuditLogEntryType,
    Sub: 'SUB' as FileHistoryAuditLogEntryType,
    Supl: 'SUPL' as FileHistoryAuditLogEntryType,
    Sval: 'SVAL' as FileHistoryAuditLogEntryType,
    Ursr: 'URSR' as FileHistoryAuditLogEntryType,
    Vrev: 'VREV' as FileHistoryAuditLogEntryType,
    Vsub: 'VSUB' as FileHistoryAuditLogEntryType
};

