/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DisputeStatus } from './disputeStatus.model';


export interface GetDisputeCountResponse { 
    status?: DisputeStatus;
    count?: number;
}
export namespace GetDisputeCountResponse {
}


