/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const JJDisputeContactType = {
    Unknown: 'UNKNOWN',
    Individual: 'INDIVIDUAL',
    Lawyer: 'LAWYER',
    Other: 'OTHER'
} as const;
export type JJDisputeContactType = typeof JJDisputeContactType[keyof typeof JJDisputeContactType];

