/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputeContactType = 'UNKNOWN' | 'INDIVIDUAL' | 'LAWYER' | 'OTHER';

export const JJDisputeContactType = {
    Unknown: 'UNKNOWN' as JJDisputeContactType,
    Individual: 'INDIVIDUAL' as JJDisputeContactType,
    Lawyer: 'LAWYER' as JJDisputeContactType,
    Other: 'OTHER' as JJDisputeContactType
};

