/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const JJDisputeStatus = {
    Unknown: 'UNKNOWN',
    New: 'NEW',
    InProgress: 'IN_PROGRESS',
    DataUpdate: 'DATA_UPDATE',
    Confirmed: 'CONFIRMED',
    RequireCourtHearing: 'REQUIRE_COURT_HEARING',
    RequireMoreInfo: 'REQUIRE_MORE_INFO',
    Accepted: 'ACCEPTED',
    Review: 'REVIEW',
    Concluded: 'CONCLUDED',
    Cancelled: 'CANCELLED',
    HearingScheduled: 'HEARING_SCHEDULED'
} as const;
export type JJDisputeStatus = typeof JJDisputeStatus[keyof typeof JJDisputeStatus];

