/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JJDisputeCourtAppearanceAmendments { 
    appearanceAmendmentId?: number | null;
    disputantSurnameNm?: string | null;
    disputantGivenNamesNm?: string | null;
    violationDateDtm?: string | null;
    otherNotesTxt?: string | null;
    count1ActSectDescTxt?: string | null;
    count1OtherTxt?: string | null;
    count2ActSectDescTxt?: string | null;
    count2OtherTxt?: string | null;
    count3ActSectDescTxt?: string | null;
    count3OtherTxt?: string | null;
    createdBy?: string | null;
    createdTs?: string | null;
    modifiedBy?: string | null;
    modifiedTs?: string | null;
    additionalProperties?: { [key: string]: any | null; } | null;
}

