/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const JJDisputeSignatoryType = {
    U: 'U',
    D: 'D',
    A: 'A'
} as const;
export type JJDisputeSignatoryType = typeof JJDisputeSignatoryType[keyof typeof JJDisputeSignatoryType];

