/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountPlea = 'GUILTY' | 'NOT_GUILTY';

export const JJDisputedCountPlea = {
    Guilty: 'GUILTY' as JJDisputedCountPlea,
    NotGuilty: 'NOT_GUILTY' as JJDisputedCountPlea
};

