/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JJDisputeRemark } from './jJDisputeRemark.model';
import { JJDisputedCount } from './jJDisputedCount.model';
import { DisputantContactInformation } from './disputantContactInformation.model';
import { JJDisputeStatus } from './jJDisputeStatus.model';


export interface JJDispute { 
    createdBy?: string | null;
    createdTs?: string;
    modifiedBy?: string | null;
    modifiedTs?: string | null;
    ticketNumber?: string | null;
    status?: JJDisputeStatus;
    submittedDate?: string | null;
    violationDate?: string | null;
    icbcReceivedDate?: string | null;
    surname?: string | null;
    givenNames?: string | null;
    enforcementOfficer?: string | null;
    policeDetachment?: string | null;
    courthouseLocation?: string | null;
    offenceLocation?: string | null;
    jjAssignedTo?: string | null;
    jjDecisionDate?: string | null;
    vtcAssignedTo?: string | null;
    vtcAssignedTs?: string | null;
    fineReductionReason?: string | null;
    timeToPayReason?: string | null;
    remarks?: Array<JJDisputeRemark> | null;
    contactInformation?: DisputantContactInformation;
    jjDisputedCounts?: Array<JJDisputedCount> | null;
    additionalProperties?: { [key: string]: any; } | null;
}

