/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const JJDisputeCourtAppearanceRoPAppCd = {
    Unknown: 'UNKNOWN',
    A: 'A',
    P: 'P',
    N: 'N'
} as const;
export type JJDisputeCourtAppearanceRoPAppCd = typeof JJDisputeCourtAppearanceRoPAppCd[keyof typeof JJDisputeCourtAppearanceRoPAppCd];

