/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountLatestPlea = 'UNKNOWN' | 'G' | 'N';

export const JJDisputedCountLatestPlea = {
    Unknown: 'UNKNOWN' as JJDisputedCountLatestPlea,
    G: 'G' as JJDisputedCountLatestPlea,
    N: 'N' as JJDisputedCountLatestPlea
};

