/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const JJDisputedCountRoPDismissed = {
    Unknown: 'UNKNOWN',
    Y: 'Y',
    N: 'N'
} as const;
export type JJDisputedCountRoPDismissed = typeof JJDisputedCountRoPDismissed[keyof typeof JJDisputedCountRoPDismissed];

