/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const JJDisputedCountRoPFinding = {
    Unknown: 'UNKNOWN',
    Guilty: 'GUILTY',
    NotGuilty: 'NOT_GUILTY',
    Cancelled: 'CANCELLED',
    PaidPriorToAppearance: 'PAID_PRIOR_TO_APPEARANCE',
    GuiltyLesser: 'GUILTY_LESSER'
} as const;
export type JJDisputedCountRoPFinding = typeof JJDisputedCountRoPFinding[keyof typeof JJDisputedCountRoPFinding];

