/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JJDisputedCountRoPForWantOfProsecution } from './jJDisputedCountRoPForWantOfProsecution.model';
import { JJDisputedCountRoPDismissed } from './jJDisputedCountRoPDismissed.model';
import { JJDisputedCountRoPWithdrawn } from './jJDisputedCountRoPWithdrawn.model';
import { JJDisputedCountRoPAbatement } from './jJDisputedCountRoPAbatement.model';
import { JJDisputedCountRoPFinding } from './jJDisputedCountRoPFinding.model';
import { JJDisputedCountRoPJailIntermittent } from './jJDisputedCountRoPJailIntermittent.model';


export interface JJDisputedCountRoP { 
    createdBy?: string | null;
    createdTs?: string;
    modifiedBy?: string | null;
    modifiedTs?: string | null;
    id?: number;
    finding?: JJDisputedCountRoPFinding;
    lesserDescription?: string | null;
    ssProbationDuration?: string | null;
    ssProbationConditions?: string | null;
    jailDuration?: string | null;
    jailIntermittent?: JJDisputedCountRoPJailIntermittent;
    probationDuration?: string | null;
    probationConditions?: string | null;
    drivingProhibition?: string | null;
    drivingProhibitionMVASection?: string | null;
    dismissed?: JJDisputedCountRoPDismissed;
    forWantOfProsecution?: JJDisputedCountRoPForWantOfProsecution;
    withdrawn?: JJDisputedCountRoPWithdrawn;
    abatement?: JJDisputedCountRoPAbatement;
    stayOfProceedingsBy?: string | null;
    other?: string | null;
    additionalProperties?: { [key: string]: any | null; } | null;
}
export namespace JJDisputedCountRoP {
}


