/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const JJDisputeHearingType = {
    Unknown: 'UNKNOWN',
    CourtAppearance: 'COURT_APPEARANCE',
    WrittenReasons: 'WRITTEN_REASONS'
} as const;
export type JJDisputeHearingType = typeof JJDisputeHearingType[keyof typeof JJDisputeHearingType];

