/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JJDisputedCountPlea } from './jJDisputedCountPlea.model';


export interface JJDisputedCount { 
    createdBy?: string | null;
    createdTs?: string;
    modifiedBy?: string | null;
    modifiedTs?: string;
    id?: number;
    plea?: JJDisputedCountPlea;
    count?: number;
    requestTimeToPay?: boolean;
    requestReduction?: boolean;
    appearInCourt?: boolean;
    description?: string | null;
    dueDate?: string | null;
    ticketedFineAmount?: number | null;
    includesSurcharge?: boolean;
    revisedDueDate?: string | null;
    totalFineAmount?: number | null;
    comments?: string | null;
    lesserOrGreaterAmount?: number;
    additionalProperties?: { [key: string]: any; } | null;
}

