/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JJDisputeCourtAppearanceRoPCrown } from './jJDisputeCourtAppearanceRoPCrown.model';
import { JJDisputeCourtAppearanceRoPAppCd } from './jJDisputeCourtAppearanceRoPAppCd.model';
import { JJDisputeCourtAppearanceRoPDattCd } from './jJDisputeCourtAppearanceRoPDattCd.model';
import { JJDisputeCourtAppearanceRoPJjSeized } from './jJDisputeCourtAppearanceRoPJjSeized.model';


export interface JJDisputeCourtAppearanceRoP { 
    justinAppearanceId?: string | null;
    id?: number | null;
    appearanceTs?: string | null;
    room?: string | null;
    duration?: number | null;
    reason?: string | null;
    appCd?: JJDisputeCourtAppearanceRoPAppCd;
    noAppTs?: string | null;
    clerkRecord?: string | null;
    defenceCounsel?: string | null;
    dattCd?: JJDisputeCourtAppearanceRoPDattCd;
    crown?: JJDisputeCourtAppearanceRoPCrown;
    jjSeized?: JJDisputeCourtAppearanceRoPJjSeized;
    adjudicator?: string | null;
    comments?: string | null;
    additionalProperties?: { [key: string]: any | null; } | null;
}
export namespace JJDisputeCourtAppearanceRoP {
}


