/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountRoPFinding = 'GUILTY' | 'NOT_GUILTY' | 'GUILTY_LESSER';

export const JJDisputedCountRoPFinding = {
    Guilty: 'GUILTY' as JJDisputedCountRoPFinding,
    NotGuilty: 'NOT_GUILTY' as JJDisputedCountRoPFinding,
    GuiltyLesser: 'GUILTY_LESSER' as JJDisputedCountRoPFinding
};

