/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountRoPWithdrawn = 'Y' | 'N';

export const JJDisputedCountRoPWithdrawn = {
    Y: 'Y' as JJDisputedCountRoPWithdrawn,
    N: 'N' as JJDisputedCountRoPWithdrawn
};

