/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputeStatus = 'NEW' | 'IN_PROGRESS' | 'COMPLETED' | 'REVIEW';

export const JJDisputeStatus = {
    New: 'NEW' as JJDisputeStatus,
    InProgress: 'IN_PROGRESS' as JJDisputeStatus,
    Completed: 'COMPLETED' as JJDisputeStatus,
    Review: 'REVIEW' as JJDisputeStatus
};

