/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a single permission.
 */
export interface Permission { 
    /**
     * The permission name.
     */
    name?: string | null;
    /**
     * A flag indicating if the user has this permission.
     */
    has?: boolean;
}

