/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SocialLinkRepresentation { 
    socialProvider?: string | null;
    socialUserId?: string | null;
    socialUsername?: string | null;
    additionalProperties?: { [key: string]: any | null; } | null;
}

