/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SortDirection = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SortDirection = typeof SortDirection[keyof typeof SortDirection];

