/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TicketImageDataJustinDocumentReportType = {
    Unknown: 'UNKNOWN',
    NoticeOfDispute: 'NOTICE_OF_DISPUTE',
    TicketImage: 'TICKET_IMAGE'
} as const;
export type TicketImageDataJustinDocumentReportType = typeof TicketImageDataJustinDocumentReportType[keyof typeof TicketImageDataJustinDocumentReportType];

