/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Count } from './count.model';


export interface Ticket { 
    number?: string | null;
    issued?: string | null;
    surname?: string | null;
    firstGivenName?: string | null;
    secondGivenName?: string | null;
    counts?: Array<Count> | null;
}

