/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CredentialRepresentation } from './credentialRepresentation.model';
import { SocialLinkRepresentation } from './socialLinkRepresentation.model';
import { FederatedIdentityRepresentation } from './federatedIdentityRepresentation.model';
import { UserConsentRepresentation } from './userConsentRepresentation.model';


export interface UserRepresentation { 
    self?: string | null;
    id?: string | null;
    createdTimestamp?: number;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    username?: string | null;
    enabled?: boolean;
    totp?: boolean;
    emailVerified?: boolean;
    attributes?: { [key: string]: Array<string> | null; } | null;
    credentials?: Array<CredentialRepresentation> | null;
    requiredActions?: Array<string> | null;
    federatedIdentities?: Array<FederatedIdentityRepresentation> | null;
    socialLinks?: Array<SocialLinkRepresentation> | null;
    realmRoles?: Array<string> | null;
    clientRoles?: { [key: string]: Array<string> | null; } | null;
    clientConsents?: Array<UserConsentRepresentation> | null;
    notBefore?: number;
    applicationRoles?: { [key: string]: Array<string> | null; } | null;
    federationLink?: string | null;
    serviceAccountClientId?: string | null;
    groups?: Array<string> | null;
    origin?: string | null;
    disableableCredentialTypes?: Array<string> | null;
    access?: { [key: string]: boolean; } | null;
    additionalProperties?: { [key: string]: any | null; } | null;
}

