/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserConsentRepresentation { 
    clientId?: string | null;
    grantedClientScopes?: Array<string> | null;
    createdDate?: number;
    lastUpdatedDate?: number;
    grantedRealmRoles?: Array<string> | null;
    additionalProperties?: { [key: string]: any; } | null;
}

