/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OcrViolationTicket } from './ocrViolationTicket.model';
import { ViolationTicketIsYoungPerson } from './violationTicketIsYoungPerson.model';
import { ViolationTicketIsDriver } from './violationTicketIsDriver.model';
import { ViolationTicketImage } from './violationTicketImage.model';
import { ViolationTicketCount } from './violationTicketCount.model';
import { ViolationTicketIsOwner } from './violationTicketIsOwner.model';
import { ViolationTicketIsChangeOfAddress } from './violationTicketIsChangeOfAddress.model';


export interface ViolationTicket { 
    createdBy?: string | null;
    createdTs?: string;
    modifiedBy?: string | null;
    modifiedTs?: string | null;
    violationTicketId?: number;
    ticketNumber?: string | null;
    disputantOrganizationName?: string | null;
    disputantSurname?: string | null;
    disputantGivenNames?: string | null;
    isYoungPerson?: ViolationTicketIsYoungPerson;
    disputantDriversLicenceNumber?: string | null;
    disputantClientNumber?: string | null;
    driversLicenceProvince?: string | null;
    driversLicenceCountry?: string | null;
    driversLicenceIssuedYear?: number | null;
    driversLicenceExpiryYear?: number | null;
    disputantBirthdate?: string | null;
    address?: string | null;
    addressCity?: string | null;
    addressProvince?: string | null;
    addressPostalCode?: string | null;
    addressCountry?: string | null;
    officerPin?: string | null;
    detachmentLocation?: string | null;
    issuedTs?: string | null;
    issuedOnRoadOrHighway?: string | null;
    issuedAtOrNearCity?: string | null;
    isChangeOfAddress?: ViolationTicketIsChangeOfAddress;
    isDriver?: ViolationTicketIsDriver;
    isOwner?: ViolationTicketIsOwner;
    courtLocation?: string | null;
    violationTicketCounts?: Array<ViolationTicketCount> | null;
    additionalProperties?: { [key: string]: any | null; } | null;
    violationTicketImage?: ViolationTicketImage;
    ocrViolationTicket?: OcrViolationTicket;
}
export namespace ViolationTicket {
}


