/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ViolationTicketVersion = 'VT1' | 'VT2';

export const ViolationTicketVersion = {
    Vt1: 'VT1' as ViolationTicketVersion,
    Vt2: 'VT2' as ViolationTicketVersion
};

