apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arc-dispute-api.fullname" . }}
  labels:
    {{- include "arc-dispute-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "arc-dispute-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "52325"
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-token: 'true'
        vault.hashicorp.com/auth-path: auth/k8s-silver
        vault.hashicorp.com/namespace: platform-services
        vault.hashicorp.com/role: {{ .Values.global.vault.role }}  # licenseplate-nonprod or licenseplate-prod are your options
        vault.hashicorp.com/agent-inject-secret-secrets.env: {{ .Values.global.vault.role }}/{{ .Values.global.vault.path }}arc-dispute-api
        vault.hashicorp.com/agent-inject-template-secrets.env: |
          {{`{{- with secret `}}"{{ .Values.global.vault.role }}/{{ .Values.global.vault.path }}arc-dispute-api"{{` }}
          {{- range $k, $v := .Data.data }}
          {{ $k }}='{{ $v }}'{{ end -}}
          {{- end `}} }}
      labels:
        {{- include "arc-dispute-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.global.licenseplate }}-vault
      containers:
        - env:
          {{- $env := merge (.Values.env | default dict) (.Values.global.env | default dict) -}}
          {{ range $k, $v := $env }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
          {{- end }}
          - name: DOTNET_DiagnosticPorts
            value: /diag/port.sock
          name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: ["/bin/sh"]
          # args: ["-c", "while true; do echo hello; sleep 10;done"]          
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /diag
            name: diagnostics
        - name: dotnet-monitor
          image: mcr.microsoft.com/dotnet/monitor
          # DO NOT use the --no-auth argument for deployments in production; this argument is used for demonstration
          # purposes only in this example. Please continue reading after this example for further details.
          args: [ "--no-auth" ]
          env:
          - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
            value: Listen
          - name: DOTNETMONITOR_DiagnosticPort__EndpointName
            value: /diag/port.sock
          - name: DOTNETMONITOR_Storage__DumpTempFolder
            value: /diag/dumps
          - name: DOTNETMONITOR_Urls
            value: http://localhost:52323
          imagePullPolicy: Always
          ports:
          - containerPort: 52325
          volumeMounts:
          - mountPath: /diag
            name: diagnostics
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
      - name: diagnostics
        emptyDir: {}      
