# Default values for form-recognizer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "acs-form-recognizer"

init:
  replicaCount: 1
  image:
    #repository: alpine
    #tag: "3.19"
    #command: ["tail", "-f", "/dev/null"]
    repository: image-registry.openshift-image-registry.svc:5000/0198bb-tools/acs-form-recognizer-init
    tag: "2.1"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.

customTemplate:
  replicaCount: 1
  image:
    repository: image-registry.openshift-image-registry.svc:5000/0198bb-tools/form-recognizer-custom-template-3.0
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "2022-08-31"

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

layout:
  replicaCount: 1
  image:
    repository: image-registry.openshift-image-registry.svc:5000/0198bb-tools/form-recognizer-layout-3.0
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "2022-08-31"

resources:
  limits:
    cpu: 3
    memory: 9Gi
  requests:
    cpu: 100m
    memory: 100Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

proxy:
  replicaCount: 1
  image:
    repository: docker.io/nginx
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "stable-alpine"

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

storage:
  logs:
    size: 500Mi
    storageClassName: ~
  shared:
    size: 1Gi
    storageClassName: ~
