export * from './dispute.service';
import { DisputeService } from './dispute.service';
export * from './document.service';
import { DocumentService } from './document.service';
export * from './documentGeneration.service';
import { DocumentGenerationService } from './documentGeneration.service';
export * from './emailHistory.service';
import { EmailHistoryService } from './emailHistory.service';
export * from './fileHistory.service';
import { FileHistoryService } from './fileHistory.service';
export * from './jJ.service';
import { JJService } from './jJ.service';
export * from './keycloak.service';
import { KeycloakService } from './keycloak.service';
export * from './lookup.service';
import { LookupService } from './lookup.service';
export const APIS = [DisputeService, DocumentService, DocumentGenerationService, EmailHistoryService, FileHistoryService, JJService, KeycloakService, LookupService];
