spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:dispute_data
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
management:
  trace:
    http:
      include: TIME_TAKEN,RESPONSE_HEADERS
  endpoints:
    web:
      exposure:
        include: httptrace,metrics,prometheus,health
