DROP TABLE VALIDATION_ERROR ;
DROP TABLE FIELD ;
DROP TABLE DOCUMENT ;
DROP SEQUENCE DOCUMENT_SEQ ;
DROP SEQUENCE FIELD_SEQ ;
DROP SEQUENCE VALIDATION_ERROR_SEQ ;

CREATE SEQUENCE DOCUMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE DOCUMENT (
	DOCUMENT_ID INT DEFAULT NEXT VALUE FOR DOCUMENT_SEQ,
	CONFIDENCE FLOAT,
	FILE_NAME VARCHAR(255),
	SOURCE VARCHAR(255),
    PRIMARY KEY (DOCUMENT_ID)
	);
	
CREATE SEQUENCE FIELD_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE FIELD (
	FIELD_ID INT DEFAULT NEXT VALUE FOR FIELD_SEQ NOT NULL,
	DOCUMENT_ID INTEGER,
	CONFIDENCE FLOAT,
	FIELD_NAME VARCHAR(255),
	RAW_CONTENT VARCHAR(255),
	CONTENT VARCHAR(255),
	PRIMARY KEY (FIELD_ID),
	FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID) ON DELETE CASCADE
	);

CREATE SEQUENCE VALIDATION_ERROR_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE VALIDATION_ERROR (
	VALIDATION_ERROR_ID INT NOT NULL,
	FIELD_ID INTEGER,
	ERROR VARCHAR(255),
	PRIMARY KEY (VALIDATION_ERROR_ID),
	FOREIGN KEY (FIELD_ID) REFERENCES FIELD (FIELD_ID) ON DELETE CASCADE
	);