apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: citizen-portal
  name: citizen-portal
spec:
  ports:
  - name: "4201"
    port: 4201
    targetPort: 8080
  selector:
    io.kompose.service: citizen-portal
status:
  loadBalancer: {}
