apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dispute-api
  name: dispute-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 8080
  selector:
    io.kompose.service: dispute-api
status:
  loadBalancer: {}
