apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dispute-api
  name: dispute-api
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: dispute-api
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
