apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    io.kompose.service: keycloak
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/traffic-court-net: "true"
        io.kompose.service: keycloak
    spec:
      containers:
      - env:
        - name: DB_VENDOR
          value: H2
        - name: KEYCLOAK_FRONTEND_URL
        - name: KEYCLOAK_IMPORT
        - name: KEYCLOAK_PASSWORD
        - name: KEYCLOAK_USER
        image: ' '
        name: keycloak
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /tmp/realm-export.json
          name: keycloak-claim0
      restartPolicy: Always
      volumes:
      - name: keycloak-claim0
        persistentVolumeClaim:
          claimName: keycloak-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - keycloak
      from:
        kind: ImageStreamTag
        name: keycloak:latest
    type: ImageChange
status: {}
