apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/keycloak/keycloak
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
