location /api/ {
    proxy_pass http://staff-api:8080/api/;
    client_max_body_size 10M;
    send_timeout 600;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;    
}
