apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: traffic-court

configMapGenerator:
  - name: ticket-search
    files:
      - config/application.properties

resources:
  - ticket-search-service.yaml
  - ticket-search-route.yaml
  - ticket-search-deployment-config.yaml
