apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: citizen-portal-demo
  name: citizen-portal-demo
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: citizen-portal-demo
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
