apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: citizen-portal
  name: citizen-portal
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: citizen-portal
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
