apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak-config
  name: keycloak-config
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: keycloak-config
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
