apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak-config
  name: keycloak-config
spec:
  replicas: 1
  selector:
    io.kompose.service: keycloak-config
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/traffic-court-net: "true"
        io.kompose.service: keycloak-config
    spec:
      containers:
      - args:
        - sh
        - -c
        - dockerize -wait http://keycloak:8080 -timeout 300s -wait-retry-interval
          10s /tmp/createuser.sh
        image: ' '
        name: keycloak-config
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - keycloak-config
      from:
        kind: ImageStreamTag
        name: keycloak-config:latest
    type: ImageChange
status: {}
