apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert --provider=openshift --build=deploy-config
      --build-repo=https://github.com/bcgov/jag-traffic-courts-online.git
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: splunk
  name: splunk
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    io.kompose.service: splunk
status:
  loadBalancer: {}
