apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dispute-api
  name: dispute-api
  namespace: 0198bb-tools
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: jag-traffic-courts-online_dispute-api
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
