/**
 * Traffic Court Online Citizen Api
 * An API for creating violation ticket disputes
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Additional { 
    lawyerPresent?: boolean;
    interpreterRequired?: boolean;
    interpreterLanguage?: string | null;
    witnessPresent?: boolean;
    numberOfWitnesses?: number | null;
    requestReduction?: boolean;
    requestMoreTime?: boolean;
    reductionReason?: string | null;
    moreTimeReason?: string | null;
}

