/**
 * Traffic Court Online Citizen Api
 * An API for creating violation ticket disputes
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddressAutocompleteRetrieveResponse { 
    id?: string | null;
    domesticId?: string | null;
    language?: string | null;
    languageAlternatives?: string | null;
    department?: string | null;
    company?: string | null;
    subBuilding?: string | null;
    buildingNumber?: string | null;
    buildingName?: string | null;
    secondaryStreet?: string | null;
    street?: string | null;
    block?: string | null;
    neighbourhood?: string | null;
    district?: string | null;
    city?: string | null;
    line1?: string | null;
    line2?: string | null;
    line3?: string | null;
    line4?: string | null;
    line5?: string | null;
    adminAreaName?: string | null;
    adminAreaCode?: string | null;
    province?: string | null;
    provinceName?: string | null;
    provinceCode?: string | null;
    postalCode?: string | null;
    countryName?: string | null;
    countryIso2?: string | null;
    countryIso3?: string | null;
    countryIsoNumber?: number;
    sortingNumber1?: string | null;
    sortingNumber2?: string | null;
    barcode?: string | null;
    poBoxNumber?: string | null;
    label?: string | null;
    dataLevel?: string | null;
}

