/**
 * Citizen API
 * Citizen API, for Citizen Portal frontend
 *
 * The version of the OpenAPI document: V0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Additional } from './additional.model';
import { OffenceDisputeDetail } from './offenceDisputeDetail.model';
import { OffenceDispute } from './offenceDispute.model';


export interface CreateOffenceDisputeCommand { 
    violationTicketNumber?: string;
    offenceNumber: number;
    violationTime?: string;
    violationDate?: string;
    additional?: Additional;
    offenceDisputeDetail?: OffenceDisputeDetail;
}

