/**
 * Traffic Court Online Citizen Api
 * An API for creating violation ticket disputes
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateShellTicketCommand { 
    violationTicketNumber?: string | null;
    violationTime?: string | null;
    violationDate?: string | null;
    lastName?: string | null;
    givenNames?: string | null;
    driverLicenseNumber?: string | null;
    birthdate?: string | null;
    gender?: string | null;
    courtHearingLocation?: string | null;
    detachmentLocation?: string | null;
    count1Charge?: number | null;
    count1FineAmount?: number | null;
    count2Charge?: number | null;
    count2FineAmount?: number | null;
    count3Charge?: number | null;
    count3FineAmount?: number | null;
    photo?: string | null;
    address?: string | null;
    city?: string | null;
    province?: string | null;
    postalCode?: string | null;
    driverLicenseProvince?: string | null;
}

