/**
 * Traffic Court Online Citizen Api
 * An API for creating violation ticket disputes
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Disputant { 
    lastName?: string | null;
    givenNames?: string | null;
    mailingAddress?: string | null;
    city?: string | null;
    province?: string | null;
    postalCode?: string | null;
    birthdate?: string | null;
    emailAddress?: string | null;
    driverLicenseNumber?: string | null;
    driverLicenseProvince?: string | null;
    phoneNumber?: string | null;
}

