/**
 * Traffic Court Online Citizen Api
 * An API for creating violation ticket disputes
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeStatus = 'UNKNOWN' | 'NEW' | 'VALIDATED' | 'PROCESSING' | 'REJECTED' | 'CANCELLED';

export const DisputeStatus = {
    Unknown: 'UNKNOWN' as DisputeStatus,
    New: 'NEW' as DisputeStatus,
    Validated: 'VALIDATED' as DisputeStatus,
    Processing: 'PROCESSING' as DisputeStatus,
    Rejected: 'REJECTED' as DisputeStatus,
    Cancelled: 'CANCELLED' as DisputeStatus
};

