/**
 * Traffic Court Online Citizen Api
 * An API for creating violation ticket disputes
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Plea } from './plea.model';


export interface DisputedCount { 
    plea?: Plea;
    /**
     * The count number. Must be unique within an individual dispute.
     */
    count?: number;
    /**
     * The disputant is requesting time to pay the ticketed amount.
     */
    request_time_to_pay?: boolean | null;
    /**
     * The disputant is requesting a reduction of the ticketed amount.
     */
    request_reduction?: boolean | null;
    /**
     * Does the want to appear in court?
     */
    appear_in_court?: boolean | null;
}

