/**
 * Traffic Court Online Citizen Api
 * An API for creating violation ticket disputes
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeCountRequestReduction = 'Y' | 'N';

export const DisputeCountRequestReduction = {
    Y: 'Y' as DisputeCountRequestReduction,
    N: 'N' as DisputeCountRequestReduction
};

