/**
 * Citizen API
 * Citizen API, for Citizen Portal frontend
 *
 * The version of the OpenAPI document: V0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DisputeStatus } from './disputeStatus.model';


export interface OffenceDisputeDetail { 
    offenceAgreementStatus?: string;
    requestReduction: boolean;
    requestMoreTime: boolean;
    reductionAppearInCourt?: boolean;
    reductionReason?: string;
    moreTimeReason?: string;
    status: DisputeStatus;
}

