/**
 * Traffic Court Online Citizen Api
 * An API for creating violation ticket disputes
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A Statute is a Violation Ticket Fine Regulation as dictated by the BC Government.
 */
export interface Statute { 
    code?: number;
    act?: string | null;
    section?: string | null;
    description?: string | null;
}

