/**
 * Traffic Court Online Citizen Api
 * An API for creating violation ticket disputes
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ViolationTicketIsYoungPerson = 'UNKNOWN' | 'Y' | 'N';

export const ViolationTicketIsYoungPerson = {
    Unknown: 'UNKNOWN' as ViolationTicketIsYoungPerson,
    Y: 'Y' as ViolationTicketIsYoungPerson,
    N: 'N' as ViolationTicketIsYoungPerson
};

