/**
 * Traffic Court Online Citizen Api
 * An API for creating violation ticket disputes
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ViolationTicketCount } from './violationTicketCount.model';


/**
 * Represents the data contained on a BC violation ticket
 */
export interface ViolationTicket { 
    /**
     * The violation ticket number.
     */
    ticket_number?: string | null;
    /**
     * The surname or corporate name.
     */
    surname?: string | null;
    /**
     * The given names or corporate name continued.
     */
    given_names?: string | null;
    /**
     * The person issued the ticket has been identified as a young person.
     */
    is_young_person?: boolean | null;
    /**
     * The drivers licence number. Note not all jurisdictions will use numeric drivers licence numbers.
     */
    drivers_licence_number?: string | null;
    /**
     * The province or state the drivers licence was issued by.
     */
    drivers_licence_province?: string | null;
    /**
     * The year the drivers licence was produced.
     */
    drivers_licence_produced_year?: number | null;
    /**
     * The year the drivers licence expires.
     */
    drivers_licence_expiry_year?: number | null;
    /**
     * The birthdate of the individual the violation ticket was issued to.
     */
    birthdate?: string | null;
    /**
     * The address of the individual the violation ticket was issued to.
     */
    address?: string | null;
    /**
     * The city of the individual the violation ticket was issued to.
     */
    city?: string | null;
    /**
     * The province or state of the individual the violation ticket was issued to.
     */
    province?: string | null;
    /**
     * The postal code or zip code.
     */
    postal_code?: string | null;
    /**
     * The address represents a change of address. The address on the violation would be different from the address   on the drivers licence or provided identification.
     */
    is_change_of_address?: boolean | null;
    /**
     * The enforcement officer says that he or she has reasonable grounds to believe, and does believe, that the above named as the vehicle driver.
     */
    is_driver?: boolean | null;
    /**
     * The enforcement officer says that he or she has reasonable grounds to believe, and does believe, that the above named as the cyclist.
     */
    is_cyclist?: boolean | null;
    /**
     * The enforcement officer says that he or she has reasonable grounds to believe, and does believe, that the above named as the vehicle owner.
     */
    is_owner?: boolean | null;
    /**
     * The enforcement officer says that he or she has reasonable grounds to believe, and does believe, that the above named as a pedestrain.
     */
    is_pedestrain?: boolean | null;
    /**
     * The enforcement officer says that he or she has reasonable grounds to believe, and does believe, that the above named as a passenger.
     */
    is_passenger?: boolean | null;
    /**
     * The enforcement officer says that he or she has reasonable grounds to believe, and does believe, that the above named as a other designation.
     */
    is_other?: boolean | null;
    /**
     * If TrafficCourts.Citizen.Service.Models.Tickets.ViolationTicket.IssuedToOther is true, the other designation description.
     */
    other_description?: string | null;
    /**
     * The date and time the violation ticket was issue. Time must only be hours and minutes.
     */
    issued_date?: string | null;
    /**
     * The violation ticket was issued on this road or highway.
     */
    issued_on_road_or_highway?: string | null;
    /**
     * The violation ticket was issued at or near this city or town.
     */
    issued_at_or_near_city?: string | null;
    /**
     * The violation ticket was issued for offence under the Motor Vehicle Act (MVA).
     */
    is_mva_offence?: boolean | null;
    /**
     * The violation ticket was issued for offence under the Wildlife Act (WLA).
     */
    is_wla_offence?: boolean | null;
    /**
     * The violation ticket was issued for offence under the Liquor Control and Licencing Act (LCA).
     */
    is_lca_offence?: boolean | null;
    /**
     * The violation ticket was issued for offence under the Motor Carrier Act (MCA).
     */
    is_mca_offence?: boolean | null;
    /**
     * The violation ticket was issued for offence under the Firearm Act (FAA).
     */
    is_faa_offence?: boolean | null;
    /**
     * The violation ticket was issued for offence under the Transit Conduct and Safety Regs (TCR).
     */
    is_tcr_offence?: boolean | null;
    /**
     * The violation ticket was issued for offence under the Commercial Transport Act (CTA).
     */
    is_cta_offence?: boolean | null;
    /**
     * The violation ticket was issued for other.
     */
    is_other_offence?: boolean | null;
    /**
     * The violation ticket was issued for other.
     */
    other_offence_description?: string | null;
    /**
     * Represents the counts identified. Must have at least one and at most three counts.
     */
    counts: Array<ViolationTicketCount>;
    /**
     * The designated provincial court hearing location. For example, Richmond, BC.
     */
    provincial_court_hearing_location?: string | null;
    /**
     * The organization or detatchment location. For example, Delta Police.
     */
    organization_location?: string | null;
}

