apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "staff-web.configmapName" . }}
  labels: {{- include "staff-web.labels" . | nindent 4 }}
data:
  app.config.json: |-
{{ include "staff-web.tplvalues.render" ( dict "value" .Values.appConfig "context" $ ) | indent 4 }}
  keycloak.config.json: |-
{{ include "staff-web.tplvalues.render" ( dict "value" .Values.keycloakConfig "context" $ ) | indent 4 }}
  nginx-api-proxy-pass.conf: |-
    client_max_body_size 10M;
    
    location /api {
      proxy_pass http://{{ .Release.Name }}-staff-api.{{ .Values.global.namespace }}.svc.cluster.local:8080/api;
      client_max_body_size 10M;
      send_timeout 600s;
      proxy_read_timeout 600s;
      proxy_send_timeout 600s;
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 2048;
    }
    error_log stderr warn;
  {{ if .Values.courtHouseDataConfig }}
  courthouse-data.json: |-
{{ include "staff-web.tplvalues.render" ( dict "value" .Values.courtHouseDataConfig "context" $ ) | indent 4 }}
  {{- end }}
