kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: rabbitmq-cluster-internal-access
spec:
  podSelector:
    matchLabels:
      app: rabbitmq-cluster
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: rabbitmq-cluster
  policyTypes:
    - Ingress
