apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "form-recognizer.fullname" . }}-proxy-config
data:
  nginx.conf: |
    worker_processes 1;

    pid /tmp/nginx.pid;
    
    events { worker_connections 1024; }

    http {

        sendfile on;
        client_max_body_size 90M;
        upstream docker-custom {
            server acs-form-recognizer-custom-template:5000;
        }

        upstream docker-layout {
            server  acs-form-recognizer-layout:5000;
        }

        server {
            listen 5000;

            location = / {
                proxy_set_header Host $host:$server_port;
                proxy_set_header Referer $scheme://$host:$server_port;
                proxy_pass http://docker-custom/;
            }

            location /status {
                proxy_pass http://docker-custom/status;
            }

            location /test {
                return 200 $scheme://$host:$server_port;
            }

            location /ready {
                proxy_pass http://docker-custom/ready;
            }

            location /swagger {
                proxy_pass http://docker-custom/swagger;
            }

            location /formrecognizer/documentModels/prebuilt-layout {
                proxy_set_header Host $host:$server_port;
                proxy_set_header Referer $scheme://$host:$server_port;

                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Headers' 'cache-control,content-type,ocp-apim-subscription-key,x-ms-useragent' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
                add_header 'Access-Control-Expose-Headers' '*' always;

                if ($request_method = 'OPTIONS') {
                    return 200;
                }

                proxy_pass http://docker-layout/formrecognizer/documentModels/prebuilt-layout;
            }

            location /formrecognizer/documentModels {
                proxy_set_header Host $host:$server_port;
                proxy_set_header Referer $scheme://$host:$server_port;

                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Headers' 'cache-control,content-type,ocp-apim-subscription-key,x-ms-useragent' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE' always;
                add_header 'Access-Control-Expose-Headers' '*' always;

                if ($request_method = 'OPTIONS') {
                    return 200;
                }

                proxy_pass http://docker-custom/formrecognizer/documentModels;
            }

            location /formrecognizer/operations {
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Headers' 'cache-control,content-type,ocp-apim-subscription-key,x-ms-useragent' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
                add_header 'Access-Control-Expose-Headers' '*' always;

                if ($request_method = OPTIONS ) {
                    return 200;
                }

                proxy_pass http://docker-custom/formrecognizer/operations;
            }
        }        
        
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;
    }
