apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "form-recognizer.fullname" . }}-proxy
  labels:
    {{- include "form-recognizer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.proxy.autoscaling.enabled }}
  replicas: {{ .Values.proxy.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "form-recognizer.fullname" . }}-proxy
      app.kubernetes.io/name: {{ include "form-recognizer.fullname" . }}-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ include "form-recognizer.fullname" . }}-proxy
        app.kubernetes.io/name: {{ include "form-recognizer.fullname" . }}-proxy
    spec:
      containers:
        - name: {{ include "form-recognizer.fullname" . }}-proxy
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          ports:
            - containerPort: 5000
              protocol: TCP
              targetPort: 5000
          # /ready will be proxied to the api
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
          volumeMounts:
            - name: configuration
              mountPath: /etc/nginx/nginx.conf
              readOnly: true
              subPath: nginx.conf
      volumes:
        - name: configuration
          configMap:
            name: {{ include "form-recognizer.fullname" . }}-proxy-config
            items:
              - key: nginx.conf
                path: nginx.conf
