apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "form-recognizer.fullname" . }}-init
  labels:
    {{- include "form-recognizer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "form-recognizer.fullname" . }}-init
      app.kubernetes.io/name: {{ include "form-recognizer.fullname" . }}-init
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ include "form-recognizer.fullname" . }}-init
        app.kubernetes.io/name: {{ include "form-recognizer.fullname" . }}-init
    spec:
      containers:
        - name: {{ include "form-recognizer.fullname" . }}-init
          image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}"
          {{- if .Values.init.image.command }}
          command: {{ .Values.init.image.command }}
          {{- end }}
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          volumeMounts:
            - name: shared
              mountPath: /shared
            - name: logs
              mountPath: /logs
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: {{ include "form-recognizer.fullname" . }}-shared
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "form-recognizer.fullname" . }}-logs
