apiVersion: v1
kind: Service
metadata:
  name: {{ include "form-recognizer.fullname" . }}-proxy
  labels:
    app.kubernetes.io/instance: {{ include "form-recognizer.fullname" . }}-proxy
    app.kubernetes.io/name: {{ include "form-recognizer.fullname" . }}-proxy
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ include "form-recognizer.fullname" . }}-proxy
    app.kubernetes.io/name: {{ include "form-recognizer.fullname" . }}-proxy
