apiVersion: v1
kind: Service
metadata:
  name: {{ include "form-recognizer.fullname" . }}-custom-template
  labels:
    app.kubernetes.io/instance: {{ include "form-recognizer.fullname" . }}-custom-template
    app.kubernetes.io/name: {{ include "form-recognizer.fullname" . }}-custom-template
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ include "form-recognizer.fullname" . }}-custom-template
    app.kubernetes.io/name: {{ include "form-recognizer.fullname" . }}-custom-template
