## Keycloak chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/keycloak/values.yaml

## Service configuration
##
service:
  ## @param service.type Kubernetes service type
  ##
  type: ClusterIP

## Keycloak pods' SecurityContext
podSecurityContext:
  enabled: false

## Keycloak containers' Security Context
containerSecurityContext:
  enabled: false
## Metrics configuration
##
metrics:
  enabled: true

keycloakConfigCli:
  enabled: false

## PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
postgresql:
  enabled: false # we are going to use a shared postgresql instance

externalDatabase:
  existingSecret: "postgres-pguser-keycloak"
  existingSecretHostKey: "pgbouncer-host"
  existingSecretPortKey: "pgbouncer-port"
  existingSecretUserKey: "user"
  existingSecretDatabaseKey: "dbname"
  existingSecretPasswordKey: "password"
