# global values
global:
  namespace: 0198bb-dev
  vault:
    role: 0198bb-nonprod
    path: dev/

arc-dispute-api:
  image:
    tag: "2.2.3"
    pullPolicy: Always
  env: 
    "Swagger__Enabled": "true"

citizen-api:
  image:
    tag: "2.2.3"
    pullPolicy: Always
  env:
    "FormRecognizer__ApiVersion": "2022-08-31"
    "FormRecognizer__ModelId": "ViolationTicket"
    "FormRecognizer__Endpoint": "https://acs-forms-recognizer-0198bb-dev.apps.silver.devops.gov.bc.ca/"
    "Swagger__Enabled": "true"
    "TicketSearch__SearchType": "Mock"
    "MassTransit__Transport": "RabbitMq"
    "COMS__BASEURL": "http://common-object-management-service:3000"
    "JWT__AUTHORITY": "https://idtest.gov.bc.ca/login"  
    "JWT__AUDIENCE": "ca.bc.gov.ag.tco.dev"
    "OAuth__USERINFOENDPOINT": "https://idtest.gov.bc.ca/oauth2/userinfo"

citizen-web:
  image:
    tag: "2.2.3"
    pullPolicy: Always
  route:
    # https://dev.justice.gov.bc.ca
    allowedIPs: "142.34.45.132"
  appConfig: |
    {
        "production": false,
        "environment": "Dev",
        "version": "2.2.3",
        "useMockServices": false,
        "apiBaseUrl": "/api",
        "understandYourTicketLink": "https://understandmyticket.gov.bc.ca/",
        "paymentOptionsLink": "https://www2.gov.bc.ca/gov/content/justice/courthouse-services/fines-payments/pay-dispute-ticket/prov-violation-tickets/pay-ticket",
        "resolutionOptionsLink": "https://www2.gov.bc.ca/gov/content/justice/courthouse-services/fines-payments/pay-dispute-ticket/prov-violation-tickets/dispute-ticket",
        "features": {
          "dispute":true
        }
      }
  authConfig: |
    {
      "authority": "https://idtest.gov.bc.ca/login",
      "clientId": "ca.bc.gov.ag.tco.dev",
      "scope": "openid profile address email",
      "responseType": "code",
      "silentRenew": true,
      "useRefreshToken": true,
      "renewTimeBeforeTokenExpiresInSeconds": 30,
      "unauthorizedRoute": "/"
    }
  oidcConfig: |
    {
    	"request_parameter_supported": false,
    	"introspection_endpoint": "https://idtest.gov.bc.ca/oauth2/introspect",
    	"claims_parameter_supported": false,
    	"scopes_supported": [
    		"openid",
    		"profile",
    		"email",
    		"address"
    	],
    	"issuer": "https://idtest.gov.bc.ca/oauth2/",
    	"id_token_encryption_enc_values_supported": [
    		"A256CBC+HS512",
    		"A256GCM",
    		"A192GCM",
    		"A128GCM",
    		"A128CBC-HS256",
    		"A192CBC-HS384",
    		"A256CBC-HS512",
    		"A128CBC+HS256"
    	],
    	"userinfo_encryption_enc_values_supported": [
    		"A256CBC+HS512",
    		"A256GCM",
    		"A192GCM",
    		"A128GCM",
    		"A128CBC-HS256",
    		"A192CBC-HS384",
    		"A256CBC-HS512",
    		"A128CBC+HS256"
    	],
    	"authorization_endpoint": "https://idtest.gov.bc.ca/login/oidc/authorize/",
    	"userinfo_signing_alg_values_supported": [
    		"PS384",
    		"RS384",
    		"RS256",
    		"none",
    		"PS256",
    		"PS512",
    		"RS512"
    	],
    	"claims_supported": [
    		"sub",
    		"street_address",
    		"country",
    		"age_19_or_over",
    		"birthdate",
    		"gender",
    		"given_names",
    		"client_id",
    		"user_type",
    		"transaction_identifier",
    		"identification_level",
    		"email",
    		"authoritative_party_name",
    		"address",
    		"locality",
    		"sector_identifier_uri",
    		"transaction_type",
    		"given_name",
    		"display_name",
    		"identity_assurance_level3",
    		"identity_assurance_level2",
    		"identity_assurance_level1",
    		"authoritative_party_identifier",
    		"identity_assurance_level",
    		"region",
    		"postal_code",
    		"family_name",
    		"age",
    		"authentication_zone_identifier"
    	],
    	"claim_types_supported": [
    		"normal"
    	],
    	"token_endpoint_auth_methods_supported": [
    		"client_secret_post",
    		"client_secret_basic",
    		"client_secret_jwt",
    		"private_key_jwt"
    	],
    	"token_endpoint": "https://idtest.gov.bc.ca/oauth2/token",
    	"response_types_supported": [
    		"code"
    	],
    	"request_uri_parameter_supported": false,
    	"userinfo_encryption_alg_values_supported": [
    		"RSA-OAEP",
    		"RSA-OAEP-256",
    		"RSA1_5"
    	],
    	"grant_types_supported": [
    		"authorization_code"
    	],
    	"revocation_endpoint": "https://idtest.gov.bc.ca/oauth2/revoke",
    	"userinfo_endpoint": "https://idtest.gov.bc.ca/oauth2/userinfo",
    	"token_endpoint_auth_signing_alg_values_supported": [
    		"PS384",
    		"ES384",
    		"RS384",
    		"HS256",
    		"HS512",
    		"ES256",
    		"RS256",
    		"HS384",
    		"ES512",
    		"PS256",
    		"PS512",
    		"RS512"
    	],
    	"id_token_encryption_alg_values_supported": [
    		"RSA-OAEP",
    		"RSA-OAEP-256",
    		"RSA1_5"
    	],
    	"jwks_uri": "https://idtest.gov.bc.ca/oauth2/jwk",
    	"subject_types_supported": [
    		"pairwise"
    	],
    	"id_token_signing_alg_values_supported": [
    		"PS384",
    		"RS384",
    		"RS256",
    		"none",
    		"PS256",
    		"PS512",
    		"RS512"
    	]
    }

oracle-data-api:
  image:
    tag: "2.2.3"
    pullPolicy: Always
  env:
    "JAVA_OPTS": "-Dlogging.level.ca.bc.gov.open.jag.tco.oracledataapi=DEBUG"
    "TZ": "America/Vancouver"
    "LOOKUP_REPOSITORY_SRC": "ords"
    "DISPUTE_REPOSITORY_SRC": "ords"
    "JJDISPUTE_REPOSITORY_SRC": "ords"
    "HISTORY_REPOSITORY_SRC": "ords"
    "ORDS_API_AUTH_ENABLED": "true"
    "REDIS_HOST": "redis-master"
    "REDIS_PORT": "6379"

staff-api:
  image:
    tag: "2.2.3"
    pullPolicy: Always
  env:    
    "Jwt__Audience": "staff-api"
    "Jwt__Authority": "https://oidc-0198bb-dev.apps.silver.devops.gov.bc.ca/realms/traffic-court"
    "KeycloakAdminApi__BaseUri": "https://oidc-0198bb-dev.apps.silver.devops.gov.bc.ca/admin/realms/"
    "KeycloakAdminApi__Realm": "traffic-court"
    "OAuth__TokenEndpoint": "https://oidc-0198bb-dev.apps.silver.devops.gov.bc.ca/realms/traffic-court/protocol/openid-connect/token"
    "Swagger__Enabled": "true"
    "MassTransit__Transport": "RabbitMq"
    "COMS__BASEURL": "http://common-object-management-service:3000"

staff-web:
  image:
    tag: "2.2.3"
    pullPolicy: Always
  route:
    # https://dev.jag.gov.bc.ca
    allowedIPs: "142.34.45.134"
  keycloakConfig: |
    {
      "config": {
        "url": "https://oidc-0198bb-dev.apps.silver.devops.gov.bc.ca/",
        "realm": "traffic-court",
        "clientId": "staff-portal"
      },
      "initOptions": {
      }
    }
  appConfig: |  
    {
        "production": false,
        "environment": "Dev",
        "version": "2.2.3",
        "useMockServices": false,
        "apiBaseUrl": "/api",
        "features": {
          "dispute":true
        }
      }

workflow-service:
  image:
    tag: "2.2.3"
    pullPolicy: Always
  env:
    "EmailConfiguration__Sender": "DoNotReply@gov.bc.ca"
    "EmailConfiguration__AllowList": ""
    "EmailConfiguration__EmailVerificationURL": "https://dev.tickets.gov.bc.ca/email/verify"
    "MassTransit__Transport": "RabbitMq"
    "COMS__BASEURL": "http://common-object-management-service:3000"
    "VIRUSSCAN__BASEURL": "http://virus-scan:8080"
  saga:
    db:
      secretName: "postgres-dev-pguser-masstransit"