# global values
global:
  namespace: 0198bb-prod
  vault:
    role: 0198bb-prod
    path: /
    
fullnameOverride: "virus-scan"

env:
  "CLAMAV__SERVER": "clamav.0198bb-prod.svc.cluster.local"

replicaCount: 3

pdb:
  create: true
