apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster
  labels:
    app: rabbitmq-cluster
spec:
  selector:
    app: rabbitmq-cluster
  clusterIP: None
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
