version: "3.8"

services:
  #############################################################################################
  ###                           Seq                                                         ###
  #############################################################################################
  seq:
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped
