apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
  name: ticket-worker
  labels:
    app: ticket-worker
    app.kubernetes.io/name: ticket-worker
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: ticket-worker
    app.kubernetes.io/part-of: traffic-court
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    name: ticket-worker
  sessionAffinity: None
  type: ClusterIP
