apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=build-config
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: github-runner
  name: github-runner
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: github-runner:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: tools/github-runner/
    git:
      ref: feature/openshift-integration
      uri: git@github.com:bcgov/jag-traffic-courts-online.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - type: ConfigChange
status:
  lastVersion: 0
