apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: github-runner
  name: github-runner
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: github-runner
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
