apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "form-recognizer.fullname" . }}-proxy-config
data:
  nginx.conf: |
    worker_processes 1;

    pid /tmp/nginx.pid;

    events { worker_connections 1024; }

    http {

        sendfile on;
        client_max_body_size 90M;
        upstream docker-api {
            server {{ include "form-recognizer.fullname" . }}-api:5000;
        }

        upstream docker-layout {
            server {{ include "form-recognizer.fullname" . }}-layout:5000;
        }

        server {
            listen 8080;

            location = / {
                proxy_set_header Host $host:$server_port;
                proxy_set_header Referer $scheme://$host:$server_port;
                proxy_pass http://docker-api/;

            }

            location /status {
                proxy_pass http://docker-api/status;

            }

            location /ready {
                proxy_pass http://docker-api/ready;

            }

            location /swagger {
                proxy_pass http://docker-api/swagger;

            }

            location /formrecognizer/v2.1/custom/ {
                proxy_set_header Host $host:$server_port;
                proxy_set_header Referer $scheme://$host:$server_port;
                proxy_pass http://docker-api/formrecognizer/v2.1/custom/;

            }

            location /formrecognizer/v2.1/layout/ {
                proxy_set_header Host $host:$server_port;
                proxy_set_header Referer $scheme://$host:$server_port;
                proxy_pass http://docker-layout/formrecognizer/v2.1/layout/;

            }
        }
        
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;
    }
