version: "3.0"

services:

# #############################################################################################
# ###                                 Github  BACKEND                                       ###
# #############################################################################################
  github-actor:
    container_name: github-actor
    build:
      context: ./github-actor
      args:
        GITHUB_PAT: ${GITHUB_TOKEN}
        GITHUB_OWNER: ${GITHUB_OWNER}
        GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
