export enum DisputeActionTypes {
  SEARCH = "[Dispute] SEARCH",
  SEARCH_SUCCESS = "[Dispute] SEARCH SUCCESS",
  SEARCH_FAILED = "[Dispute] SEARCH FAILED",
  
  UPDATE_CONTACT = "[Dispute] UPDATE CONTACT",
  UPDATE_CONTACT_SUCCESS = "[Dispute] UPDATE CONTACT SUCCESS",
  UPDATE_CONTACT_FAILED = "[Dispute] UPDATE CONTACT FAILED",

  GET = "[Dispute] GET",
  GET_SUCCESS = "[Dispute] GET SUCCESS",
  GET_FAILED = "[Dispute] GET FAILED",
    
  UPDATE = "[Dispute] UPDATE",
  UPDATE_SUCCESS = "[Dispute] UPDATE SUCCESS",
  UPDATE_FAILED = "[Dispute] UPDATE FAILED",
};
