export enum DisputeActionTypes {
  SEARCH = "[Dispute] SEARCH",
  SEARCH_SUCCESS = "[Dispute] SEARCH SUCCESS",
  SEARCH_FAILED = "[Dispute] SEARCH FAILED",
  
  UPDATE_CONTACT = "[Dispute] UPDATE CONTACT",
  UPDATE_CONTACT_SUCCESS = "[Dispute] UPDATE CONTACT SUCCESS",
  UPDATE_CONTACT_FAILED = "[Dispute] UPDATE CONTACT FAILED",

  GET = "[Dispute] GET",
  GET_SUCCESS = "[Dispute] GET SUCCESS",
  GET_FAILED = "[Dispute] GET FAILED",
    
  UPDATE = "[Dispute] UPDATE",
  UPDATE_SUCCESS = "[Dispute] UPDATE SUCCESS",
  UPDATE_FAILED = "[Dispute] UPDATE FAILED",
    
  GET_DOCUMENT = "[Dispute] GET DOCUMENT",
  GET_DOCUMENT_SUCCESS = "[Dispute] GET DOCUMENT SUCCESS",
  GET_DOCUMENT_FAILED = "[Dispute] GET DOCUMENT FAILED",
    
  ADD_DOCUMENT = "[Dispute] ADD DOCUMENT",
  ADD_DOCUMENT_SUCCESS = "[Dispute] ADD DOCUMENT SUCCESS",
  ADD_DOCUMENT_FAILED = "[Dispute] ADD DOCUMENT FAILED",
    
  REMOVE_DOCUMENT = "[Dispute] REMOVE DOCUMENT",
  REMOVE_DOCUMENT_SUCCESS = "[Dispute] REMOVE DOCUMENT SUCCESS",
  REMOVE_DOCUMENT_FAILED = "[Dispute] REMOVE DOCUMENT FAILED",
};
