apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle-data-api.fullname" . }}
  labels:
    {{- include "oracle-data-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oracle-data-api.selectorLabels" . | nindent 4 }}
