openapi: 3.0.3
info:
  description: This is an Oracle REST Data Services (ORDS) service for the Online Court Case Management solution.
  title: Online Court Case Management
  version: 1.0.0
servers:
  - description: local
    url: 'https://ords-0198bb-dev.apps.silver.devops.gov.bc.ca/tcoords/tco/'
paths:
  /v1/ping:
    get:
      operationId: ping
      summary: Pings the server to test the connection
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResult'
      tags:
        - Health
components:
  schemas:
    PingResult:
      type: object
      properties:
        status:
          type: string
        currentTimestamp:
          type: string
          format: date-time
