using Microsoft.EntityFrameworkCore;
using Oracle.DataDictionary;

namespace CrudGenerator;

public static class CrudOperation
{
    public const string Insert = "Insert";
    public const string Update = "Update";
    public const string Delete = "Delete";
    public const string Select = "Select";
}

public record SourceTable
{
    public string Name { get; init; } = string.Empty;

    public ColumnProperty[] Properties { get; set; } = Array.Empty<ColumnProperty>();

    /// <summary>
    /// The crud operations that should be generated. If empty, all operations are generated.
    /// </summary>
    public string[] Operations { get; init; } = Array.Empty<string>();

    /// <summary>
    /// Determines if the specific operation should be created for this table.
    /// </summary>
    /// <param name="operation"></param>
    /// <returns></returns>
    public bool CreateOperation(string operation)
    {
        if (Operations.Length == 0)
        {
            return true;
        }
        else
        {
            return Operations.Contains(operation);
        }
    }

    /// <summary>
    /// The name of the sequence that generates the primary key for the table.
    /// Not actually used in the code generation as the primary key is generated by a trigger.
    /// </summary>
    public string PrimaryKeySequenceName { get; init; } = string.Empty;

    /// <summary>
    /// The abbreviation of the table.
    /// </summary>
    public string Abbreviation { get; init; } = string.Empty;
}

public class ColumnProperty
{
    /// <summary>
    /// The column name.
    /// </summary>
    public string Name { get; init; } = string.Empty;

    /// <summary>
    /// The format of the column when serialized to JSON.
    /// </summary>
    public string Format { get; set; } = "yyyy-MM-dd HH:mm:ss";
    /// <summary>
    /// The DateTimeKind to use when we deserialize the value.
    /// </summary>
    public DateTimeKind DateTimeKind { get; set; } = DateTimeKind.Unspecified;
}

public record SourceTableCollection
{
    public string Schema { get; init; } = string.Empty;

    /// <summary>
    /// Common audit columns that are used in all tables.
    /// </summary>
    public List<string> AuditColumns { get; init; } = new List<string>();
    public List<SourceTable> Tables { get; init; } = new List<SourceTable>();
}
