kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: node
  namespace: 0198bb-tools
  labels:
    usage: build-pipeline-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '20.16'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/node:20.16'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '18.20.4'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/node:18.20.4'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '18.12.1'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/node:18.12.1'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '18.12'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/node:18.12'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '16.18.1'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/node:16.18.1'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
