kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: pipelines-git-init-rhel8
  namespace: 0198bb-tools
  labels:
    usage: build-pipeline-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 'v1.8.1-52'
      from:
        kind: DockerImage
        name: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8:v1.8.1-52'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: 'v1.6.1-4'
      from:
        kind: DockerImage
        name: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8:v1.6.1-4'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
