kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: rabbitmq
  namespace: 0198bb-tools
  labels:
    usage: runtime-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '3.13.6-debian-12-r1'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/bitnami/rabbitmq:3.13.6-debian-12-r1'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '3.12.13-debian-12-r2'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/bitnami/rabbitmq:3.12.13-debian-12-r2'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '3.12-debian-11'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/bitnami/rabbitmq:3.12-debian-11'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '3.12.6-debian-11-r11'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/bitnami/rabbitmq:3.12.6-debian-11-r11'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '3.12.0-debian-11-r0'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/bitnami/rabbitmq:3.12.0-debian-11-r0'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '3.11.9-debian-11-r2'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/bitnami/rabbitmq:3.11.9-debian-11-r2'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
