kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: redis-cluster
  namespace: 0198bb-tools
  labels:
    usage: runtime-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '7.4.0-debian-12-r0'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/bitnami/redis-cluster:7.4.0-debian-12-r0'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '7.2.4-debian-12-r9'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/bitnami/redis-cluster:7.2.4-debian-12-r9'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
