export const CourtLocations = [
  { id: 1, name: '100 Mile House' },
  { id: 2, name: 'Abbotsford' },
  { id: 3, name: 'Alexis Creek' },
  { id: 4, name: 'Anahim Lake' },
  { id: 5, name: 'Ashcroft' },
  { id: 6, name: 'Atlin' },
  { id: 7, name: 'Bella Bella' },
  { id: 8, name: 'Bella Coola' },
  { id: 9, name: 'Burns Lake' },
  { id: 10, name: 'Campbell River' },
  { id: 11, name: 'Castlegar' },
  { id: 12, name: 'Chase' },
  { id: 13, name: 'Chetwynd' },
  { id: 14, name: 'Chilliwack' },
  { id: 15, name: 'Clearwater' },
  { id: 16, name: 'Courtenay' },
  { id: 17, name: 'Cranbrook' },
  { id: 18, name: 'Dawson Creek' },
  { id: 19, name: 'Dease Lake' },
  { id: 20, name: 'Duncan' },
  { id: 21, name: 'Fernie' },
  { id: 22, name: 'Fort Nelson' },
  { id: 23, name: 'Fort St. James' },
  { id: 24, name: 'Fort St. John' },
  { id: 25, name: 'Fraser Lake' },
  { id: 26, name: 'Ganges' },
  { id: 27, name: 'Gold River' },
  { id: 28, name: 'Golden' },
  { id: 29, name: 'Good Hope Lake' },
  { id: 30, name: 'Grand Forks' },
  { id: 31, name: 'Hazelton' },
  { id: 32, name: 'Houston' },
  { id: 33, name: "Hudson's Hope" },
  { id: 34, name: 'Invermere' },
  { id: 35, name: 'Kamloops' },
  { id: 36, name: 'Kelowna' },
  { id: 37, name: 'Kitimat' },
  { id: 38, name: 'Klemtu' },
  { id: 39, name: 'Kwadacha (Fort Ware)' },
  { id: 40, name: 'Lillooet' },
  { id: 41, name: 'Lower Post' },
  { id: 42, name: 'Mackenzie' },
  { id: 43, name: 'Masset' },
  { id: 44, name: 'McBride' },
  { id: 45, name: 'Merritt' },
  { id: 46, name: 'Nakusp' },
  { id: 47, name: 'Nanaimo' },
  { id: 48, name: 'Nelson' },
  { id: 49, name: 'New Aiyansh' },
  { id: 50, name: 'New Westminster' },
  { id: 51, name: 'North Vancouver' },
  { id: 52, name: 'Pemberton' },
  { id: 53, name: 'Penticton' },
  { id: 54, name: 'Port Alberni' },
  { id: 55, name: 'Port Coquitlam' },
  { id: 56, name: 'Port Hardy' },
  { id: 57, name: 'Powell River' },
  { id: 58, name: 'Prince George' },
  { id: 59, name: 'Prince Rupert' },
  { id: 60, name: 'Princeton' },
  { id: 61, name: 'Queen Charlotte City' },
  { id: 62, name: 'Quesnel' },
  { id: 63, name: 'Revelstoke' },
  { id: 64, name: 'Richmond' },
  { id: 65, name: 'Rossland' },
  { id: 66, name: 'Salmon Arm' },
  { id: 67, name: 'Sechelt' },
  { id: 68, name: 'Sidney' },
  { id: 69, name: 'Smithers' },
  { id: 70, name: 'Sparwood' },
  { id: 71, name: 'Stewart' },
  { id: 72, name: 'Surrey' },
  { id: 73, name: 'Tahsis' },
  { id: 74, name: 'Terrace' },
  { id: 75, name: 'Tofino' },
  { id: 76, name: 'Tsay Keh Dene' },
  { id: 77, name: 'Tumbler Ridge' },
  { id: 78, name: 'Ucluelet' },
  { id: 82, name: 'Vernon' },
  { id: 79, name: 'Valemount' },
  { id: 80, name: 'Vancouver' },
  { id: 81, name: 'Vanderhoof' },
  { id: 83, name: 'Victoria' },
  { id: 84, name: 'Western Communities' },
  { id: 85, name: 'Williams Lake' },
];
