//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace TrafficCourts.OrdsDataService.Occam;

#nullable enable
/// <summary>
/// Represents a row in the occam_audit_log_entries table.
/// </summary>
public partial class OccamAuditLogEntries : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "occam_audit_log_entries";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("audit_log_entry_id")]
    public long? AuditLogEntryId
    {
        get { return BackingStore.Get<long?>("audit_log_entry_id"); }
        set { BackingStore.Set<long?>("audit_log_entry_id", value, isKey: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_id")]
    public long? DisputeId
    {
        get { return BackingStore.Get<long?>("dispute_id"); }
        set { BackingStore.Set<long?>("dispute_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("audit_log_entry_type_cd")]
    public string? AuditLogEntryTypeCd
    {
        get { return BackingStore.Get<string?>("audit_log_entry_type_cd"); }
        set { BackingStore.Set<string?>("audit_log_entry_type_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("action_by_application_user")]
    public string? ActionByApplicationUser
    {
        get { return BackingStore.Get<string?>("action_by_application_user"); }
        set { BackingStore.Set<string?>("action_by_application_user", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("comment_txt")]
    public string? CommentTxt
    {
        get { return BackingStore.Get<string?>("comment_txt"); }
        set { BackingStore.Set<string?>("comment_txt", value); }
    }
}

/// <summary>
/// Represents a row in the occam_dispute_counts table.
/// </summary>
public partial class OccamDisputeCounts : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "occam_dispute_counts";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("dispute_count_id")]
    public long? DisputeCountId
    {
        get { return BackingStore.Get<long?>("dispute_count_id"); }
        set { BackingStore.Set<long?>("dispute_count_id", value, isKey: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_id")]
    public long? DisputeId
    {
        get { return BackingStore.Get<long?>("dispute_id"); }
        set { BackingStore.Set<long?>("dispute_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("violation_ticket_count_id")]
    public long? ViolationTicketCountId
    {
        get { return BackingStore.Get<long?>("violation_ticket_count_id"); }
        set { BackingStore.Set<long?>("violation_ticket_count_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("stat_id")]
    public int? StatId
    {
        get { return BackingStore.Get<int?>("stat_id"); }
        set { BackingStore.Set<int?>("stat_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("plea_cd")]
    public string? PleaCd
    {
        get { return BackingStore.Get<string?>("plea_cd"); }
        set { BackingStore.Set<string?>("plea_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("request_court_appearance_yn")]
    public string? RequestCourtAppearanceYn
    {
        get { return BackingStore.Get<string?>("request_court_appearance_yn"); }
        set { BackingStore.Set<string?>("request_court_appearance_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("request_reduction_yn")]
    public string? RequestReductionYn
    {
        get { return BackingStore.Get<string?>("request_reduction_yn"); }
        set { BackingStore.Set<string?>("request_reduction_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("request_time_to_pay_yn")]
    public string? RequestTimeToPayYn
    {
        get { return BackingStore.Get<string?>("request_time_to_pay_yn"); }
        set { BackingStore.Set<string?>("request_time_to_pay_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }
}

/// <summary>
/// Represents a row in the occam_dispute_update_requests table.
/// </summary>
public partial class OccamDisputeUpdateRequests : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "occam_dispute_update_requests";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("dispute_update_request_id")]
    public long? DisputeUpdateRequestId
    {
        get { return BackingStore.Get<long?>("dispute_update_request_id"); }
        set { BackingStore.Set<long?>("dispute_update_request_id", value, isKey: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_id")]
    public long? DisputeId
    {
        get { return BackingStore.Get<long?>("dispute_id"); }
        set { BackingStore.Set<long?>("dispute_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_update_stat_type_cd")]
    public string? DisputeUpdateStatTypeCd
    {
        get { return BackingStore.Get<string?>("dispute_update_stat_type_cd"); }
        set { BackingStore.Set<string?>("dispute_update_stat_type_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_update_req_type_cd")]
    public string? DisputeUpdateReqTypeCd
    {
        get { return BackingStore.Get<string?>("dispute_update_req_type_cd"); }
        set { BackingStore.Set<string?>("dispute_update_req_type_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("request_json_txt")]
    public string? RequestJsonTxt
    {
        get { return BackingStore.Get<string?>("request_json_txt"); }
        set { BackingStore.Set<string?>("request_json_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("current_json_txt")]
    public string? CurrentJsonTxt
    {
        get { return BackingStore.Get<string?>("current_json_txt"); }
        set { BackingStore.Set<string?>("current_json_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("status_update_dtm")]
    public DateTime? StatusUpdateDtm
    {
        get { return BackingStore.GetDateTime("status_update_dtm", format: "yyyy-MM-dd HH:mm:ss", kind: DateTimeKind.Utc); }
        set { BackingStore.SetDateTime("status_update_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }
}

/// <summary>
/// Represents a row in the occam_disputes table.
/// </summary>
public partial class OccamDisputes : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "occam_disputes";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("dispute_id")]
    public long? DisputeId
    {
        get { return BackingStore.Get<long?>("dispute_id"); }
        set { BackingStore.Set<long?>("dispute_id", value, isKey: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("court_agen_id")]
    public decimal? CourtAgenId
    {
        get { return BackingStore.Get<decimal?>("court_agen_id"); }
        set { BackingStore.Set<decimal?>("court_agen_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_status_type_cd")]
    public string? DisputeStatusTypeCd
    {
        get { return BackingStore.Get<string?>("dispute_status_type_cd"); }
        set { BackingStore.Set<string?>("dispute_status_type_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("contact_type_cd")]
    public string? ContactTypeCd
    {
        get { return BackingStore.Get<string?>("contact_type_cd"); }
        set { BackingStore.Set<string?>("contact_type_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("request_court_appearance_yn")]
    public string? RequestCourtAppearanceYn
    {
        get { return BackingStore.Get<string?>("request_court_appearance_yn"); }
        set { BackingStore.Set<string?>("request_court_appearance_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("violation_ticket_upload_id")]
    public long? ViolationTicketUploadId
    {
        get { return BackingStore.Get<long?>("violation_ticket_upload_id"); }
        set { BackingStore.Set<long?>("violation_ticket_upload_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("issued_dt")]
    public DateTime? IssuedDt
    {
        get { return BackingStore.GetDateTime("issued_dt", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("issued_dt", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("submitted_dt")]
    public DateTime? SubmittedDt
    {
        get { return BackingStore.GetDateTime("submitted_dt", format: "yyyy-MM-dd HH:mm:ss", kind: DateTimeKind.Utc); }
        set { BackingStore.SetDateTime("submitted_dt", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_surname_nm")]
    public string? DisputantSurnameNm
    {
        get { return BackingStore.Get<string?>("disputant_surname_nm"); }
        set { BackingStore.Set<string?>("disputant_surname_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_given_1_nm")]
    public string? DisputantGiven1Nm
    {
        get { return BackingStore.Get<string?>("disputant_given_1_nm"); }
        set { BackingStore.Set<string?>("disputant_given_1_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_given_2_nm")]
    public string? DisputantGiven2Nm
    {
        get { return BackingStore.Get<string?>("disputant_given_2_nm"); }
        set { BackingStore.Set<string?>("disputant_given_2_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_given_3_nm")]
    public string? DisputantGiven3Nm
    {
        get { return BackingStore.Get<string?>("disputant_given_3_nm"); }
        set { BackingStore.Set<string?>("disputant_given_3_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_birth_dt")]
    public DateTime? DisputantBirthDt
    {
        get { return BackingStore.GetDateTime("disputant_birth_dt", format: "yyyy-MM-dd"); }
        set { BackingStore.SetDateTime("disputant_birth_dt", value, format: "yyyy-MM-dd"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_organization_nm")]
    public string? DisputantOrganizationNm
    {
        get { return BackingStore.Get<string?>("disputant_organization_nm"); }
        set { BackingStore.Set<string?>("disputant_organization_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_drv_lic_number_txt")]
    public string? DisputantDrvLicNumberTxt
    {
        get { return BackingStore.Get<string?>("disputant_drv_lic_number_txt"); }
        set { BackingStore.Set<string?>("disputant_drv_lic_number_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("drv_lic_issued_prov_ctry_id")]
    public int? DrvLicIssuedProvCtryId
    {
        get { return BackingStore.Get<int?>("drv_lic_issued_prov_ctry_id"); }
        set { BackingStore.Set<int?>("drv_lic_issued_prov_ctry_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("drv_lic_issued_prov_seq_no")]
    public short? DrvLicIssuedProvSeqNo
    {
        get { return BackingStore.Get<short?>("drv_lic_issued_prov_seq_no"); }
        set { BackingStore.Set<short?>("drv_lic_issued_prov_seq_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("drv_lic_issued_ctry_ctry_id")]
    public int? DrvLicIssuedCtryCtryId
    {
        get { return BackingStore.Get<int?>("drv_lic_issued_ctry_ctry_id"); }
        set { BackingStore.Set<int?>("drv_lic_issued_ctry_ctry_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("drv_lic_issued_other_prov_txt")]
    public string? DrvLicIssuedOtherProvTxt
    {
        get { return BackingStore.Get<string?>("drv_lic_issued_other_prov_txt"); }
        set { BackingStore.Set<string?>("drv_lic_issued_other_prov_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_client_id")]
    public string? DisputantClientId
    {
        get { return BackingStore.Get<string?>("disputant_client_id"); }
        set { BackingStore.Set<string?>("disputant_client_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_line_1_txt")]
    public string? AddressLine1Txt
    {
        get { return BackingStore.Get<string?>("address_line_1_txt"); }
        set { BackingStore.Set<string?>("address_line_1_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_line_2_txt")]
    public string? AddressLine2Txt
    {
        get { return BackingStore.Get<string?>("address_line_2_txt"); }
        set { BackingStore.Set<string?>("address_line_2_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_line_3_txt")]
    public string? AddressLine3Txt
    {
        get { return BackingStore.Get<string?>("address_line_3_txt"); }
        set { BackingStore.Set<string?>("address_line_3_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_city_ctry_id")]
    public int? AddressCityCtryId
    {
        get { return BackingStore.Get<int?>("address_city_ctry_id"); }
        set { BackingStore.Set<int?>("address_city_ctry_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_city_seq_no")]
    public short? AddressCitySeqNo
    {
        get { return BackingStore.Get<short?>("address_city_seq_no"); }
        set { BackingStore.Set<short?>("address_city_seq_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_prov_ctry_id")]
    public int? AddressProvCtryId
    {
        get { return BackingStore.Get<int?>("address_prov_ctry_id"); }
        set { BackingStore.Set<int?>("address_prov_ctry_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_prov_seq_no")]
    public short? AddressProvSeqNo
    {
        get { return BackingStore.Get<short?>("address_prov_seq_no"); }
        set { BackingStore.Set<short?>("address_prov_seq_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_ctry_ctry_id")]
    public int? AddressCtryCtryId
    {
        get { return BackingStore.Get<int?>("address_ctry_ctry_id"); }
        set { BackingStore.Set<int?>("address_ctry_ctry_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_other_city_txt")]
    public string? AddressOtherCityTxt
    {
        get { return BackingStore.Get<string?>("address_other_city_txt"); }
        set { BackingStore.Set<string?>("address_other_city_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_other_prov_txt")]
    public string? AddressOtherProvTxt
    {
        get { return BackingStore.Get<string?>("address_other_prov_txt"); }
        set { BackingStore.Set<string?>("address_other_prov_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("postal_code_txt")]
    public string? PostalCodeTxt
    {
        get { return BackingStore.Get<string?>("postal_code_txt"); }
        set { BackingStore.Set<string?>("postal_code_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("home_phone_number_txt")]
    public string? HomePhoneNumberTxt
    {
        get { return BackingStore.Get<string?>("home_phone_number_txt"); }
        set { BackingStore.Set<string?>("home_phone_number_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("contact_law_firm_nm")]
    public string? ContactLawFirmNm
    {
        get { return BackingStore.Get<string?>("contact_law_firm_nm"); }
        set { BackingStore.Set<string?>("contact_law_firm_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("contact_surname_nm")]
    public string? ContactSurnameNm
    {
        get { return BackingStore.Get<string?>("contact_surname_nm"); }
        set { BackingStore.Set<string?>("contact_surname_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("contact_given_1_nm")]
    public string? ContactGiven1Nm
    {
        get { return BackingStore.Get<string?>("contact_given_1_nm"); }
        set { BackingStore.Set<string?>("contact_given_1_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("contact_given_2_nm")]
    public string? ContactGiven2Nm
    {
        get { return BackingStore.Get<string?>("contact_given_2_nm"); }
        set { BackingStore.Set<string?>("contact_given_2_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("contact_given_3_nm")]
    public string? ContactGiven3Nm
    {
        get { return BackingStore.Get<string?>("contact_given_3_nm"); }
        set { BackingStore.Set<string?>("contact_given_3_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("work_phone_number_txt")]
    public string? WorkPhoneNumberTxt
    {
        get { return BackingStore.Get<string?>("work_phone_number_txt"); }
        set { BackingStore.Set<string?>("work_phone_number_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("email_address_txt")]
    public string? EmailAddressTxt
    {
        get { return BackingStore.Get<string?>("email_address_txt"); }
        set { BackingStore.Set<string?>("email_address_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("email_verified_yn")]
    public string? EmailVerifiedYn
    {
        get { return BackingStore.Get<string?>("email_verified_yn"); }
        set { BackingStore.Set<string?>("email_verified_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("notice_of_dispute_guid")]
    public string? NoticeOfDisputeGuid
    {
        get { return BackingStore.Get<string?>("notice_of_dispute_guid"); }
        set { BackingStore.Set<string?>("notice_of_dispute_guid", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("filing_dt")]
    public DateTime? FilingDt
    {
        get { return BackingStore.GetDateTime("filing_dt", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("filing_dt", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("represented_by_lawyer_yn")]
    public string? RepresentedByLawyerYn
    {
        get { return BackingStore.Get<string?>("represented_by_lawyer_yn"); }
        set { BackingStore.Set<string?>("represented_by_lawyer_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("law_firm_nm")]
    public string? LawFirmNm
    {
        get { return BackingStore.Get<string?>("law_firm_nm"); }
        set { BackingStore.Set<string?>("law_firm_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("law_firm_addr_line_1_txt")]
    public string? LawFirmAddrLine1Txt
    {
        get { return BackingStore.Get<string?>("law_firm_addr_line_1_txt"); }
        set { BackingStore.Set<string?>("law_firm_addr_line_1_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("law_firm_addr_line_2_txt")]
    public string? LawFirmAddrLine2Txt
    {
        get { return BackingStore.Get<string?>("law_firm_addr_line_2_txt"); }
        set { BackingStore.Set<string?>("law_firm_addr_line_2_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("law_firm_addr_line_3_txt")]
    public string? LawFirmAddrLine3Txt
    {
        get { return BackingStore.Get<string?>("law_firm_addr_line_3_txt"); }
        set { BackingStore.Set<string?>("law_firm_addr_line_3_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("law_firm_addr_city_ctry_id")]
    public int? LawFirmAddrCityCtryId
    {
        get { return BackingStore.Get<int?>("law_firm_addr_city_ctry_id"); }
        set { BackingStore.Set<int?>("law_firm_addr_city_ctry_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("law_firm_addr_city_seq_no")]
    public short? LawFirmAddrCitySeqNo
    {
        get { return BackingStore.Get<short?>("law_firm_addr_city_seq_no"); }
        set { BackingStore.Set<short?>("law_firm_addr_city_seq_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("law_firm_addr_prov_ctry_id")]
    public int? LawFirmAddrProvCtryId
    {
        get { return BackingStore.Get<int?>("law_firm_addr_prov_ctry_id"); }
        set { BackingStore.Set<int?>("law_firm_addr_prov_ctry_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("law_firm_addr_prov_seq_no")]
    public short? LawFirmAddrProvSeqNo
    {
        get { return BackingStore.Get<short?>("law_firm_addr_prov_seq_no"); }
        set { BackingStore.Set<short?>("law_firm_addr_prov_seq_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("law_firm_addr_ctry_ctry_id")]
    public int? LawFirmAddrCtryCtryId
    {
        get { return BackingStore.Get<int?>("law_firm_addr_ctry_ctry_id"); }
        set { BackingStore.Set<int?>("law_firm_addr_ctry_ctry_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("law_firm_addr_other_city_txt")]
    public string? LawFirmAddrOtherCityTxt
    {
        get { return BackingStore.Get<string?>("law_firm_addr_other_city_txt"); }
        set { BackingStore.Set<string?>("law_firm_addr_other_city_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("law_firm_addr_other_prov_txt")]
    public string? LawFirmAddrOtherProvTxt
    {
        get { return BackingStore.Get<string?>("law_firm_addr_other_prov_txt"); }
        set { BackingStore.Set<string?>("law_firm_addr_other_prov_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("law_firm_addr_postal_code_txt")]
    public string? LawFirmAddrPostalCodeTxt
    {
        get { return BackingStore.Get<string?>("law_firm_addr_postal_code_txt"); }
        set { BackingStore.Set<string?>("law_firm_addr_postal_code_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("lawyer_surname_nm")]
    public string? LawyerSurnameNm
    {
        get { return BackingStore.Get<string?>("lawyer_surname_nm"); }
        set { BackingStore.Set<string?>("lawyer_surname_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("lawyer_given_1_nm")]
    public string? LawyerGiven1Nm
    {
        get { return BackingStore.Get<string?>("lawyer_given_1_nm"); }
        set { BackingStore.Set<string?>("lawyer_given_1_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("lawyer_given_2_nm")]
    public string? LawyerGiven2Nm
    {
        get { return BackingStore.Get<string?>("lawyer_given_2_nm"); }
        set { BackingStore.Set<string?>("lawyer_given_2_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("lawyer_given_3_nm")]
    public string? LawyerGiven3Nm
    {
        get { return BackingStore.Get<string?>("lawyer_given_3_nm"); }
        set { BackingStore.Set<string?>("lawyer_given_3_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("lawyer_phone_number_txt")]
    public string? LawyerPhoneNumberTxt
    {
        get { return BackingStore.Get<string?>("lawyer_phone_number_txt"); }
        set { BackingStore.Set<string?>("lawyer_phone_number_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("lawyer_email_address_txt")]
    public string? LawyerEmailAddressTxt
    {
        get { return BackingStore.Get<string?>("lawyer_email_address_txt"); }
        set { BackingStore.Set<string?>("lawyer_email_address_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("officer_pin_txt")]
    public string? OfficerPinTxt
    {
        get { return BackingStore.Get<string?>("officer_pin_txt"); }
        set { BackingStore.Set<string?>("officer_pin_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("detachment_location_txt")]
    public string? DetachmentLocationTxt
    {
        get { return BackingStore.Get<string?>("detachment_location_txt"); }
        set { BackingStore.Set<string?>("detachment_location_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("language_cd")]
    public string? LanguageCd
    {
        get { return BackingStore.Get<string?>("language_cd"); }
        set { BackingStore.Set<string?>("language_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("interpreter_required_yn")]
    public string? InterpreterRequiredYn
    {
        get { return BackingStore.Get<string?>("interpreter_required_yn"); }
        set { BackingStore.Set<string?>("interpreter_required_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("witness_no")]
    public short? WitnessNo
    {
        get { return BackingStore.Get<short?>("witness_no"); }
        set { BackingStore.Set<short?>("witness_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("fine_reduction_reason_txt")]
    public string? FineReductionReasonTxt
    {
        get { return BackingStore.Get<string?>("fine_reduction_reason_txt"); }
        set { BackingStore.Set<string?>("fine_reduction_reason_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("time_to_pay_reason_txt")]
    public string? TimeToPayReasonTxt
    {
        get { return BackingStore.Get<string?>("time_to_pay_reason_txt"); }
        set { BackingStore.Set<string?>("time_to_pay_reason_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_comment_txt")]
    public string? DisputantCommentTxt
    {
        get { return BackingStore.Get<string?>("disputant_comment_txt"); }
        set { BackingStore.Set<string?>("disputant_comment_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("rejected_reason_txt")]
    public string? RejectedReasonTxt
    {
        get { return BackingStore.Get<string?>("rejected_reason_txt"); }
        set { BackingStore.Set<string?>("rejected_reason_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("jj_assigned_to")]
    public string? JjAssignedTo
    {
        get { return BackingStore.Get<string?>("jj_assigned_to"); }
        set { BackingStore.Set<string?>("jj_assigned_to", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("user_assigned_to")]
    public string? UserAssignedTo
    {
        get { return BackingStore.Get<string?>("user_assigned_to"); }
        set { BackingStore.Set<string?>("user_assigned_to", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("user_assigned_dtm")]
    public DateTime? UserAssignedDtm
    {
        get { return BackingStore.GetDateTime("user_assigned_dtm", format: "yyyy-MM-dd HH:mm:ss", kind: DateTimeKind.Utc); }
        set { BackingStore.SetDateTime("user_assigned_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_detect_ocr_issues_yn")]
    public string? DisputantDetectOcrIssuesYn
    {
        get { return BackingStore.Get<string?>("disputant_detect_ocr_issues_yn"); }
        set { BackingStore.Set<string?>("disputant_detect_ocr_issues_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_ocr_issues_txt")]
    public string? DisputantOcrIssuesTxt
    {
        get { return BackingStore.Get<string?>("disputant_ocr_issues_txt"); }
        set { BackingStore.Set<string?>("disputant_ocr_issues_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("system_detect_ocr_issues_yn")]
    public string? SystemDetectOcrIssuesYn
    {
        get { return BackingStore.Get<string?>("system_detect_ocr_issues_yn"); }
        set { BackingStore.Set<string?>("system_detect_ocr_issues_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ocr_ticket_json_filename_txt")]
    public string? OcrTicketJsonFilenameTxt
    {
        get { return BackingStore.Get<string?>("ocr_ticket_json_filename_txt"); }
        set { BackingStore.Set<string?>("ocr_ticket_json_filename_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("signatory_type_cd")]
    public string? SignatoryTypeCd
    {
        get { return BackingStore.Get<string?>("signatory_type_cd"); }
        set { BackingStore.Set<string?>("signatory_type_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("signatory_name_txt")]
    public string? SignatoryNameTxt
    {
        get { return BackingStore.Get<string?>("signatory_name_txt"); }
        set { BackingStore.Set<string?>("signatory_name_txt", value); }
    }
}

/// <summary>
/// Represents a row in the occam_error_logs table.
/// </summary>
public partial class OccamErrorLogs : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "occam_error_logs";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("error_log_id")]
    public long? ErrorLogId
    {
        get { return BackingStore.Get<long?>("error_log_id"); }
        set { BackingStore.Set<long?>("error_log_id", value, isKey: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("error_message_no")]
    public long? ErrorMessageNo
    {
        get { return BackingStore.Get<long?>("error_message_no"); }
        set { BackingStore.Set<long?>("error_message_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("error_message_txt")]
    public string? ErrorMessageTxt
    {
        get { return BackingStore.Get<string?>("error_message_txt"); }
        set { BackingStore.Set<string?>("error_message_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("program_nm")]
    public string? ProgramNm
    {
        get { return BackingStore.Get<string?>("program_nm"); }
        set { BackingStore.Set<string?>("program_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("program_version_txt")]
    public string? ProgramVersionTxt
    {
        get { return BackingStore.Get<string?>("program_version_txt"); }
        set { BackingStore.Set<string?>("program_version_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("error_detail_txt")]
    public string? ErrorDetailTxt
    {
        get { return BackingStore.Get<string?>("error_detail_txt"); }
        set { BackingStore.Set<string?>("error_detail_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }
}

/// <summary>
/// Represents a row in the occam_outgoing_emails table.
/// </summary>
public partial class OccamOutgoingEmails : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "occam_outgoing_emails";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("outgoing_email_id")]
    public long? OutgoingEmailId
    {
        get { return BackingStore.Get<long?>("outgoing_email_id"); }
        set { BackingStore.Set<long?>("outgoing_email_id", value, isKey: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_id")]
    public long? DisputeId
    {
        get { return BackingStore.Get<long?>("dispute_id"); }
        set { BackingStore.Set<long?>("dispute_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("email_sent_dtm")]
    public DateTime? EmailSentDtm
    {
        get { return BackingStore.GetDateTime("email_sent_dtm", format: "yyyy-MM-dd HH:mm:ss", kind: DateTimeKind.Utc); }
        set { BackingStore.SetDateTime("email_sent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("email_subject_txt")]
    public string? EmailSubjectTxt
    {
        get { return BackingStore.Get<string?>("email_subject_txt"); }
        set { BackingStore.Set<string?>("email_subject_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("from_email_address")]
    public string? FromEmailAddress
    {
        get { return BackingStore.Get<string?>("from_email_address"); }
        set { BackingStore.Set<string?>("from_email_address", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("to_email_address")]
    public string? ToEmailAddress
    {
        get { return BackingStore.Get<string?>("to_email_address"); }
        set { BackingStore.Set<string?>("to_email_address", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("cc_email_address")]
    public string? CcEmailAddress
    {
        get { return BackingStore.Get<string?>("cc_email_address"); }
        set { BackingStore.Set<string?>("cc_email_address", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("bcc_email_address")]
    public string? BccEmailAddress
    {
        get { return BackingStore.Get<string?>("bcc_email_address"); }
        set { BackingStore.Set<string?>("bcc_email_address", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("successfully_sent_yn")]
    public string? SuccessfullySentYn
    {
        get { return BackingStore.Get<string?>("successfully_sent_yn"); }
        set { BackingStore.Set<string?>("successfully_sent_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("html_content")]
    public string? HtmlContent
    {
        get { return BackingStore.Get<string?>("html_content"); }
        set { BackingStore.Set<string?>("html_content", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("plain_text_content")]
    public string? PlainTextContent
    {
        get { return BackingStore.Get<string?>("plain_text_content"); }
        set { BackingStore.Set<string?>("plain_text_content", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }
}

/// <summary>
/// Represents a row in the occam_violation_ticket_counts table.
/// </summary>
public partial class OccamViolationTicketCounts : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "occam_violation_ticket_counts";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("violation_ticket_count_id")]
    public long? ViolationTicketCountId
    {
        get { return BackingStore.Get<long?>("violation_ticket_count_id"); }
        set { BackingStore.Set<long?>("violation_ticket_count_id", value, isKey: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("violation_ticket_upload_id")]
    public long? ViolationTicketUploadId
    {
        get { return BackingStore.Get<long?>("violation_ticket_upload_id"); }
        set { BackingStore.Set<long?>("violation_ticket_upload_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("count_no")]
    public short? CountNo
    {
        get { return BackingStore.Get<short?>("count_no"); }
        set { BackingStore.Set<short?>("count_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("description_txt")]
    public string? DescriptionTxt
    {
        get { return BackingStore.Get<string?>("description_txt"); }
        set { BackingStore.Set<string?>("description_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("is_act_yn")]
    public string? IsActYn
    {
        get { return BackingStore.Get<string?>("is_act_yn"); }
        set { BackingStore.Set<string?>("is_act_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("is_regulation_yn")]
    public string? IsRegulationYn
    {
        get { return BackingStore.Get<string?>("is_regulation_yn"); }
        set { BackingStore.Set<string?>("is_regulation_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("act_or_regulation_name_cd")]
    public string? ActOrRegulationNameCd
    {
        get { return BackingStore.Get<string?>("act_or_regulation_name_cd"); }
        set { BackingStore.Set<string?>("act_or_regulation_name_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("stat_section_txt")]
    public string? StatSectionTxt
    {
        get { return BackingStore.Get<string?>("stat_section_txt"); }
        set { BackingStore.Set<string?>("stat_section_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("stat_sub_section_txt")]
    public string? StatSubSectionTxt
    {
        get { return BackingStore.Get<string?>("stat_sub_section_txt"); }
        set { BackingStore.Set<string?>("stat_sub_section_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("stat_paragraph_txt")]
    public string? StatParagraphTxt
    {
        get { return BackingStore.Get<string?>("stat_paragraph_txt"); }
        set { BackingStore.Set<string?>("stat_paragraph_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("stat_sub_paragraph_txt")]
    public string? StatSubParagraphTxt
    {
        get { return BackingStore.Get<string?>("stat_sub_paragraph_txt"); }
        set { BackingStore.Set<string?>("stat_sub_paragraph_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ticketed_amt")]
    public decimal? TicketedAmt
    {
        get { return BackingStore.Get<decimal?>("ticketed_amt"); }
        set { BackingStore.Set<decimal?>("ticketed_amt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }
}

/// <summary>
/// Represents a row in the occam_violation_ticket_uploads table.
/// </summary>
public partial class OccamViolationTicketUploads : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "occam_violation_ticket_uploads";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("violation_ticket_upload_id")]
    public long? ViolationTicketUploadId
    {
        get { return BackingStore.Get<long?>("violation_ticket_upload_id"); }
        set { BackingStore.Set<long?>("violation_ticket_upload_id", value, isKey: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ticket_number_txt")]
    public string? TicketNumberTxt
    {
        get { return BackingStore.Get<string?>("ticket_number_txt"); }
        set { BackingStore.Set<string?>("ticket_number_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_surname_txt")]
    public string? DisputantSurnameTxt
    {
        get { return BackingStore.Get<string?>("disputant_surname_txt"); }
        set { BackingStore.Set<string?>("disputant_surname_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_given_names_txt")]
    public string? DisputantGivenNamesTxt
    {
        get { return BackingStore.Get<string?>("disputant_given_names_txt"); }
        set { BackingStore.Set<string?>("disputant_given_names_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_organization_nm_txt")]
    public string? DisputantOrganizationNmTxt
    {
        get { return BackingStore.Get<string?>("disputant_organization_nm_txt"); }
        set { BackingStore.Set<string?>("disputant_organization_nm_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("is_young_person_yn")]
    public string? IsYoungPersonYn
    {
        get { return BackingStore.Get<string?>("is_young_person_yn"); }
        set { BackingStore.Set<string?>("is_young_person_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_drv_lic_number_txt")]
    public string? DisputantDrvLicNumberTxt
    {
        get { return BackingStore.Get<string?>("disputant_drv_lic_number_txt"); }
        set { BackingStore.Set<string?>("disputant_drv_lic_number_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_client_number_txt")]
    public string? DisputantClientNumberTxt
    {
        get { return BackingStore.Get<string?>("disputant_client_number_txt"); }
        set { BackingStore.Set<string?>("disputant_client_number_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("drv_lic_issued_province_txt")]
    public string? DrvLicIssuedProvinceTxt
    {
        get { return BackingStore.Get<string?>("drv_lic_issued_province_txt"); }
        set { BackingStore.Set<string?>("drv_lic_issued_province_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("drv_lic_issued_country_txt")]
    public string? DrvLicIssuedCountryTxt
    {
        get { return BackingStore.Get<string?>("drv_lic_issued_country_txt"); }
        set { BackingStore.Set<string?>("drv_lic_issued_country_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("drv_lic_issued_year_no")]
    public short? DrvLicIssuedYearNo
    {
        get { return BackingStore.Get<short?>("drv_lic_issued_year_no"); }
        set { BackingStore.Set<short?>("drv_lic_issued_year_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("drv_lic_expiry_year_no")]
    public short? DrvLicExpiryYearNo
    {
        get { return BackingStore.Get<short?>("drv_lic_expiry_year_no"); }
        set { BackingStore.Set<short?>("drv_lic_expiry_year_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_birth_dt")]
    public DateTime? DisputantBirthDt
    {
        get { return BackingStore.GetDateTime("disputant_birth_dt", format: "yyyy-MM-dd"); }
        set { BackingStore.SetDateTime("disputant_birth_dt", value, format: "yyyy-MM-dd"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_txt")]
    public string? AddressTxt
    {
        get { return BackingStore.Get<string?>("address_txt"); }
        set { BackingStore.Set<string?>("address_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_city_txt")]
    public string? AddressCityTxt
    {
        get { return BackingStore.Get<string?>("address_city_txt"); }
        set { BackingStore.Set<string?>("address_city_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_province_txt")]
    public string? AddressProvinceTxt
    {
        get { return BackingStore.Get<string?>("address_province_txt"); }
        set { BackingStore.Set<string?>("address_province_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_country_txt")]
    public string? AddressCountryTxt
    {
        get { return BackingStore.Get<string?>("address_country_txt"); }
        set { BackingStore.Set<string?>("address_country_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("address_postal_code_txt")]
    public string? AddressPostalCodeTxt
    {
        get { return BackingStore.Get<string?>("address_postal_code_txt"); }
        set { BackingStore.Set<string?>("address_postal_code_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("officer_pin_txt")]
    public string? OfficerPinTxt
    {
        get { return BackingStore.Get<string?>("officer_pin_txt"); }
        set { BackingStore.Set<string?>("officer_pin_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("detachment_location_txt")]
    public string? DetachmentLocationTxt
    {
        get { return BackingStore.Get<string?>("detachment_location_txt"); }
        set { BackingStore.Set<string?>("detachment_location_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("issued_dt")]
    public DateTime? IssuedDt
    {
        get { return BackingStore.GetDateTime("issued_dt", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("issued_dt", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("issued_on_road_or_highway_txt")]
    public string? IssuedOnRoadOrHighwayTxt
    {
        get { return BackingStore.Get<string?>("issued_on_road_or_highway_txt"); }
        set { BackingStore.Set<string?>("issued_on_road_or_highway_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("issued_at_or_near_city_txt")]
    public string? IssuedAtOrNearCityTxt
    {
        get { return BackingStore.Get<string?>("issued_at_or_near_city_txt"); }
        set { BackingStore.Set<string?>("issued_at_or_near_city_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("is_change_of_address_yn")]
    public string? IsChangeOfAddressYn
    {
        get { return BackingStore.Get<string?>("is_change_of_address_yn"); }
        set { BackingStore.Set<string?>("is_change_of_address_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("is_driver_yn")]
    public string? IsDriverYn
    {
        get { return BackingStore.Get<string?>("is_driver_yn"); }
        set { BackingStore.Set<string?>("is_driver_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("is_owner_yn")]
    public string? IsOwnerYn
    {
        get { return BackingStore.Get<string?>("is_owner_yn"); }
        set { BackingStore.Set<string?>("is_owner_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("court_location_txt")]
    public string? CourtLocationTxt
    {
        get { return BackingStore.Get<string?>("court_location_txt"); }
        set { BackingStore.Set<string?>("court_location_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }
}

