name: Build Workflow Service

# This workflow will automatically build the workflow-service project on the creation of a tag in Github.
# The build is then pushed to Openshift, tagged with the gitsha and the release tag, ie. workflow-service:5adf53, workflow-service:1.2.3

on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: 'Release version tag (e.g. 1.2.3)'
        required: true
        type: string
      GIT_REVISION:
        description: 'Git revision to use for the image tag (e.g. abc1234)'
        required: true
        type: string
        default: 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to OpenShift
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      - name: Build and push
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: ./src/backend/TrafficCourts
          DOCKERFILE: ./src/backend/TrafficCourts/Workflow.Service/Dockerfile.rhel8
          IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/workflow-service
          RELEASE_VERSION: ${{ inputs.RELEASE_VERSION }}
          GIT_REVISION: ${{ inputs.GIT_REVISION }}
        run: |
          build_uid=$(cat /proc/sys/kernel/random/uuid | tr -d '-' | cut -c1-8)

          echo "Building workflow-service:${GIT_REVISION}-${build_uid}"

          docker build \
            --build-arg GIT_SHA=${GIT_REVISION} \
            --build-arg GIT_SHORT_SHA=${GIT_REVISION} \
            --build-arg GIT_VERSION=${RELEASE_VERSION} \
            --tag ${IMAGE}:${GIT_REVISION}-${build_uid} \
            -f ${DOCKERFILE} \
            ${CONTEXT}

          # Always push with the unique build tag
          docker push ${IMAGE}:${GIT_REVISION}-${build_uid}

          # Tag as latest
          docker tag ${IMAGE}:${GIT_REVISION}-${build_uid} ${IMAGE}:latest
          docker push ${IMAGE}:latest

          # Tag with the release version
          docker tag ${IMAGE}:${GIT_REVISION}-${build_uid} ${IMAGE}:${RELEASE_VERSION}
          docker push ${IMAGE}:${RELEASE_VERSION}
          echo "Tagged: workflow-service:${RELEASE_VERSION}"
