name: Build tools
on:
  push:
    branches: [tools]
  workflow_dispatch:
    branches: [tools]

jobs:
  build-tools:
    runs-on: ubuntu-20.04
    env:
      name: tools
      VERSION: v1
      IMAGE_NAME: github-actor
      IMAGE_TAGS: latest
     
    steps:
      - uses: actions/checkout@v2

      - name: Build the Image
        id: build-image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |          
          docker login ${{ secrets.REDHAT_REPO }} -u ${{ secrets.REDHAT_REPO_USER }} -p ${{ secrets.REDHAT_REPO_AUTH }}
          cd tools
          docker-compose -f ${{ github.workspace }}/tools/docker-compose.yml build \
          --build-arg RUNNER_NAME="${{ secrets.RUNNER_NAME }}" \
          --build-arg GITHUB_PAT="${{ secrets.RUNNER_PAT }} \"
          --build-arg GITHUB_REPOSITORY="${{ secrets.RUNNER_REPOSITORY }}" \ 
          --build-arg GITHUB_OWNER="${{ secrets.RUNNER_OWNER }}"

      - name: Tag the Image
        id: tag-image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker tag tools_${{ env.IMAGE_NAME }} ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}/${{ env.IMAGE_NAME }}

      - name: Push To Registry via Docker
        id: push-image-docker
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker login ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }} -u ${{ secrets.OPENSHIFT_SA_USERNAME }} -p ${{ secrets.OPENSHIFT_SA_PASSWORD }}
          docker image push --all-tags ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}/${{ env.IMAGE_NAME }}
