name: Frontend PR Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux]

    env:
      VERSION: v1
      IMAGE_NAME: citizen-portal
      IMAGE_TAGS: latest
     
    steps:
      - uses: actions/checkout@v2

      - name: Build the Image
        id: build-image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |          
          docker login ${{ secrets.REDHAT_REPO }} -u ${{ secrets.REDHAT_REPO_USER }} -p ${{ secrets.REDHAT_REPO_AUTH }}
          docker-compose -f ${{ github.workspace }}/docker-compose.yml build \
          --build-arg USE_MOCK_SERVICES=${{ secrets.USE_MOCK_SERVICES }} \
          --build-arg USE_KEYCLOAK= "true" \
          --build-arg API_URL=${{ secrets.API_URL }} \
          --build-arg KEYCLOAK_URL=${{ secrets.KEYCLOAK_URL }} \
          --build-arg KEYCLOAK_REALM=${{ secrets.KEYCLOAK_REALM }} \
          --build-arg KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }} \
          ${{ env.IMAGE_NAME }} 
