name: Main-Generate Coverage Reports

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  
  workflow_dispatch:

jobs:
  frontend:
    name: Generate Javascript coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
      - name: Install Yarn
        run: npm install -g yarn
        
      # Figure out where yarn is caching things
      - name: Yarn Cache
        run: yarn cache dir

      # Implement Caching Action for Yarn Project
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # YARN cache files are stored in `/home/runner/.cache/yarn/v6` on git actions
          path: /home/runner/.cache/yarn/v6
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Run Yarn Install - citizen Portal
      - name: Run Yarn Install - citizen Portal
        run: yarn --cwd src/frontend/citizen-portal install

      # Run lint - citizen Portal
      - name: Run lint - citizen Portal
        run: yarn --cwd src/frontend/citizen-portal run lint

      # Yarn Coverage - citizen Portal
      - name: Run Yarn Coverage - citizen Portal
        run: yarn --cwd ${{github.workspace}}/src/frontend/citizen-portal coverage

      # Upload coverage for debugging purposes
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: citizen-portal-coverage-report
          path: ${{github.workspace}}/src/frontend/citizen-portal/coverage/

  backend:
    name: Generate .NET Backend coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Run the .NET Coverage report for Backend - DisputeAPI & TrafficCourts
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Generate .NET Code Coverage - CitizenAPI
        run: dotnet test ${{github.workspace}}/src/backend/TrafficCourts /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:ExcludeByFile=\"**/*.g.cs\"

      # Upload coverage for debugging purposes
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: ${{github.workspace}}/src/backend/TrafficCourts/

