name: Build NodeJS Image
on: [pull_request]

jobs:
  build-main:
    runs-on: ubuntu-20.04
    environment: Development
    env:
      VERSION: v1
      IMAGE_NAME: citizen-portal
      IMAGE_TAGS: latest
      API_URL: ${{ secrets.API_URL }}
      KEYCLOAK_URL: ${{ secrets.KEYCLOAK_URL }}
      KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
      KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
      USE_MOCK_SERVICES: ${{ secrets.USE_MOCK_SERVICES }}
      USE_KEYCLOAK: ${{ secrets.USE_KEYCLOAK }}
    steps:
      - uses: actions/checkout@v2

      - name: Build the Image
        id: build-image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |          
          docker login ${{ secrets.REDHAT_REPO }} \
            -u ${{ secrets.REDHAT_REPO_USER }} \
            -p ${{ secrets.REDHAT_REPO_AUTH }}
          docker-compose build --force-rm --no-cache \
            --build-arg API_URL=${{ secrets.API_URL }} \
            --build-arg KEYCLOAK_URL=${{ secrets.KEYCLOAK_URL }} \
            --build-arg KEYCLOAK_REALM=${{ secrets.KEYCLOAK_REALM }} \
            --build-arg KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }} \
            --build-arg USE_MOCK_SERVICES=${{ secrets.USE_MOCK_SERVICES }} \
            --build-arg USE_KEYCLOAK=${{ secrets.USE_KEYCLOAK }} \
            $IMAGE_NAME
