name: Build NodeJS Image

on:
  pull_request:
    paths:
      - 'src/frontend/citizen-portal/**'

jobs:
  build-main:
    runs-on: ubuntu-20.04
    environment: Development
    env:
      VERSION: v1
      IMAGE_NAME: citizen-portal
      IMAGE_TAGS: latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Image
        id: build-image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          CONTEXT: ./src/frontend/citizen-portal
          DOCKER_BUILDKIT: 1
        run: |          
          docker build ${CONTEXT}
