  
# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
# 
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Labeler
on: [pull_request]

jobs:
  label:
    environment: Development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      # only label if the GITHUB_TOKEN is available, PRs from external repos do not have access to secrets vars
      if: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
