name: Ticket Search

on:
  pull_request:
    paths:
      - 'src/ticket-search/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: build ticket-search
        run: dotnet build
        working-directory: ./src/ticket-search
      - name: test ticket-search
        run: dotnet test
        working-directory: ./src/ticket-search
