name: Pull and Push Jaeger Image

on:
  workflow_dispatch:

env:
  SOURCE_IMAGE: jaegertracing/all-in-one:latest
  TARGET_IMAGE_NAME: jaeger

jobs:
  copy-image:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to OpenShift registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}
          username: ${{ secrets.OPENSHIFT_SA_USERNAME }}
          password: ${{ secrets.OPENSHIFT_SA_PASSWORD }}

      - name: Pull source image
        run: docker pull "${SOURCE_IMAGE}"

      - name: Tag image for OpenShift registry
        run: |
          docker tag "${SOURCE_IMAGE}" "${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}/${TARGET_IMAGE_NAME}:latest"

      - name: Push image to OpenShift registry
        run: |
          docker push "${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}/${TARGET_IMAGE_NAME}:latest"
