//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace TrafficCourts.OrdsDataService.Tco;

#nullable enable
/// <summary>
/// Represents a row in the tco_appearance_charge_counts table.
/// </summary>
public partial class TcoAppearanceChargeCounts : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "tco_appearance_charge_counts";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("appearance_charge_count_id")]
    public long? AppearanceChargeCountId
    {
        get { return BackingStore.Get<long?>("appearance_charge_count_id"); }
        set { BackingStore.Set<long?>("appearance_charge_count_id", value, alwaysDirty: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("court_appearance_id")]
    public long? CourtAppearanceId
    {
        get { return BackingStore.Get<long?>("court_appearance_id"); }
        set { BackingStore.Set<long?>("court_appearance_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_count_id")]
    public long? DisputeCountId
    {
        get { return BackingStore.Get<long?>("dispute_count_id"); }
        set { BackingStore.Set<long?>("dispute_count_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("finding_result_cd")]
    public string? FindingResultCd
    {
        get { return BackingStore.Get<string?>("finding_result_cd"); }
        set { BackingStore.Set<string?>("finding_result_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("lesser_charge_desc_txt")]
    public string? LesserChargeDescTxt
    {
        get { return BackingStore.Get<string?>("lesser_charge_desc_txt"); }
        set { BackingStore.Set<string?>("lesser_charge_desc_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("susp_sntc_probation_durtn_txt")]
    public string? SuspSntcProbationDurtnTxt
    {
        get { return BackingStore.Get<string?>("susp_sntc_probation_durtn_txt"); }
        set { BackingStore.Set<string?>("susp_sntc_probation_durtn_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("susp_sntc_probation_conds_txt")]
    public string? SuspSntcProbationCondsTxt
    {
        get { return BackingStore.Get<string?>("susp_sntc_probation_conds_txt"); }
        set { BackingStore.Set<string?>("susp_sntc_probation_conds_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("jail_duration_txt")]
    public string? JailDurationTxt
    {
        get { return BackingStore.Get<string?>("jail_duration_txt"); }
        set { BackingStore.Set<string?>("jail_duration_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("jail_intermittent_yn")]
    public string? JailIntermittentYn
    {
        get { return BackingStore.Get<string?>("jail_intermittent_yn"); }
        set { BackingStore.Set<string?>("jail_intermittent_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("probation_duration_txt")]
    public string? ProbationDurationTxt
    {
        get { return BackingStore.Get<string?>("probation_duration_txt"); }
        set { BackingStore.Set<string?>("probation_duration_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("probation_conditions_txt")]
    public string? ProbationConditionsTxt
    {
        get { return BackingStore.Get<string?>("probation_conditions_txt"); }
        set { BackingStore.Set<string?>("probation_conditions_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("driving_prohib_duration_txt")]
    public string? DrivingProhibDurationTxt
    {
        get { return BackingStore.Get<string?>("driving_prohib_duration_txt"); }
        set { BackingStore.Set<string?>("driving_prohib_duration_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("driving_prohib_mva_section_txt")]
    public string? DrivingProhibMvaSectionTxt
    {
        get { return BackingStore.Get<string?>("driving_prohib_mva_section_txt"); }
        set { BackingStore.Set<string?>("driving_prohib_mva_section_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dismissed_yn")]
    public string? DismissedYn
    {
        get { return BackingStore.Get<string?>("dismissed_yn"); }
        set { BackingStore.Set<string?>("dismissed_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dismissed_for_want_prosec_yn")]
    public string? DismissedForWantProsecYn
    {
        get { return BackingStore.Get<string?>("dismissed_for_want_prosec_yn"); }
        set { BackingStore.Set<string?>("dismissed_for_want_prosec_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("withdrawn_yn")]
    public string? WithdrawnYn
    {
        get { return BackingStore.Get<string?>("withdrawn_yn"); }
        set { BackingStore.Set<string?>("withdrawn_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("abatement_yn")]
    public string? AbatementYn
    {
        get { return BackingStore.Get<string?>("abatement_yn"); }
        set { BackingStore.Set<string?>("abatement_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("stay_of_proceedings_by_txt")]
    public string? StayOfProceedingsByTxt
    {
        get { return BackingStore.Get<string?>("stay_of_proceedings_by_txt"); }
        set { BackingStore.Set<string?>("stay_of_proceedings_by_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("other_txt")]
    public string? OtherTxt
    {
        get { return BackingStore.Get<string?>("other_txt"); }
        set { BackingStore.Set<string?>("other_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("remarks_txt")]
    public string? RemarksTxt
    {
        get { return BackingStore.Get<string?>("remarks_txt"); }
        set { BackingStore.Set<string?>("remarks_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }
}

/// <summary>
/// Represents a row in the tco_audit_log_entries table.
/// </summary>
public partial class TcoAuditLogEntries : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "tco_audit_log_entries";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("audit_log_entry_id")]
    public long? AuditLogEntryId
    {
        get { return BackingStore.Get<long?>("audit_log_entry_id"); }
        set { BackingStore.Set<long?>("audit_log_entry_id", value, alwaysDirty: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_id")]
    public long? DisputeId
    {
        get { return BackingStore.Get<long?>("dispute_id"); }
        set { BackingStore.Set<long?>("dispute_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("audit_log_entry_type_cd")]
    public string? AuditLogEntryTypeCd
    {
        get { return BackingStore.Get<string?>("audit_log_entry_type_cd"); }
        set { BackingStore.Set<string?>("audit_log_entry_type_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("action_by_application_user")]
    public string? ActionByApplicationUser
    {
        get { return BackingStore.Get<string?>("action_by_application_user"); }
        set { BackingStore.Set<string?>("action_by_application_user", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("comment_txt")]
    public string? CommentTxt
    {
        get { return BackingStore.Get<string?>("comment_txt"); }
        set { BackingStore.Set<string?>("comment_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }
}

/// <summary>
/// Represents a row in the tco_court_appearances table.
/// </summary>
public partial class TcoCourtAppearances : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "tco_court_appearances";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("court_appearance_id")]
    public long? CourtAppearanceId
    {
        get { return BackingStore.Get<long?>("court_appearance_id"); }
        set { BackingStore.Set<long?>("court_appearance_id", value, alwaysDirty: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_id")]
    public long? DisputeId
    {
        get { return BackingStore.Get<long?>("dispute_id"); }
        set { BackingStore.Set<long?>("dispute_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("appearance_dtm")]
    public DateTime? AppearanceDtm
    {
        get { return BackingStore.GetDateTime("appearance_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("appearance_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("courtroom_number_txt")]
    public string? CourtroomNumberTxt
    {
        get { return BackingStore.Get<string?>("courtroom_number_txt"); }
        set { BackingStore.Set<string?>("courtroom_number_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("appearance_reason_txt")]
    public string? AppearanceReasonTxt
    {
        get { return BackingStore.Get<string?>("appearance_reason_txt"); }
        set { BackingStore.Set<string?>("appearance_reason_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_presence_cd")]
    public string? DisputantPresenceCd
    {
        get { return BackingStore.Get<string?>("disputant_presence_cd"); }
        set { BackingStore.Set<string?>("disputant_presence_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("disputant_not_present_dtm")]
    public DateTime? DisputantNotPresentDtm
    {
        get { return BackingStore.GetDateTime("disputant_not_present_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("disputant_not_present_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("recording_clerk_name_txt")]
    public string? RecordingClerkNameTxt
    {
        get { return BackingStore.Get<string?>("recording_clerk_name_txt"); }
        set { BackingStore.Set<string?>("recording_clerk_name_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("defence_counsel_name_txt")]
    public string? DefenceCounselNameTxt
    {
        get { return BackingStore.Get<string?>("defence_counsel_name_txt"); }
        set { BackingStore.Set<string?>("defence_counsel_name_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("crown_presence_cd")]
    public string? CrownPresenceCd
    {
        get { return BackingStore.Get<string?>("crown_presence_cd"); }
        set { BackingStore.Set<string?>("crown_presence_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("seized_yn")]
    public string? SeizedYn
    {
        get { return BackingStore.Get<string?>("seized_yn"); }
        set { BackingStore.Set<string?>("seized_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("judge_or_jj_name_txt")]
    public string? JudgeOrJjNameTxt
    {
        get { return BackingStore.Get<string?>("judge_or_jj_name_txt"); }
        set { BackingStore.Set<string?>("judge_or_jj_name_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("comments_txt")]
    public string? CommentsTxt
    {
        get { return BackingStore.Get<string?>("comments_txt"); }
        set { BackingStore.Set<string?>("comments_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("justin_appr_id")]
    public decimal? JustinApprId
    {
        get { return BackingStore.Get<decimal?>("justin_appr_id"); }
        set { BackingStore.Set<decimal?>("justin_appr_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("defence_counsel_presence_cd")]
    public string? DefenceCounselPresenceCd
    {
        get { return BackingStore.Get<string?>("defence_counsel_presence_cd"); }
        set { BackingStore.Set<string?>("defence_counsel_presence_cd", value); }
    }
}

/// <summary>
/// Represents a row in the tco_dispute_counts table.
/// </summary>
public partial class TcoDisputeCounts : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "tco_dispute_counts";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("dispute_count_id")]
    public long? DisputeCountId
    {
        get { return BackingStore.Get<long?>("dispute_count_id"); }
        set { BackingStore.Set<long?>("dispute_count_id", value, alwaysDirty: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_id")]
    public long? DisputeId
    {
        get { return BackingStore.Get<long?>("dispute_id"); }
        set { BackingStore.Set<long?>("dispute_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("count_no")]
    public short? CountNo
    {
        get { return BackingStore.Get<short?>("count_no"); }
        set { BackingStore.Set<short?>("count_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("violation_ticket_count_id")]
    public long? ViolationTicketCountId
    {
        get { return BackingStore.Get<long?>("violation_ticket_count_id"); }
        set { BackingStore.Set<long?>("violation_ticket_count_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ticket_inbox_count_seq_no")]
    public short? TicketInboxCountSeqNo
    {
        get { return BackingStore.Get<short?>("ticket_inbox_count_seq_no"); }
        set { BackingStore.Set<short?>("ticket_inbox_count_seq_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ticket_inbox_entry_id")]
    public long? TicketInboxEntryId
    {
        get { return BackingStore.Get<long?>("ticket_inbox_entry_id"); }
        set { BackingStore.Set<long?>("ticket_inbox_entry_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("justin_stat_id")]
    public int? JustinStatId
    {
        get { return BackingStore.Get<int?>("justin_stat_id"); }
        set { BackingStore.Set<int?>("justin_stat_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("initial_plea_cd")]
    public string? InitialPleaCd
    {
        get { return BackingStore.Get<string?>("initial_plea_cd"); }
        set { BackingStore.Set<string?>("initial_plea_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("fine_due_dt")]
    public DateTime? FineDueDt
    {
        get { return BackingStore.GetDateTime("fine_due_dt", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("fine_due_dt", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("adjusted_amt")]
    public decimal? AdjustedAmt
    {
        get { return BackingStore.Get<decimal?>("adjusted_amt"); }
        set { BackingStore.Set<decimal?>("adjusted_amt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("includes_surcharge_yn")]
    public string? IncludesSurchargeYn
    {
        get { return BackingStore.Get<string?>("includes_surcharge_yn"); }
        set { BackingStore.Set<string?>("includes_surcharge_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("revised_due_dt")]
    public DateTime? RevisedDueDt
    {
        get { return BackingStore.GetDateTime("revised_due_dt", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("revised_due_dt", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("total_fine_amt")]
    public decimal? TotalFineAmt
    {
        get { return BackingStore.Get<decimal?>("total_fine_amt"); }
        set { BackingStore.Set<decimal?>("total_fine_amt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("comments_txt")]
    public string? CommentsTxt
    {
        get { return BackingStore.Get<string?>("comments_txt"); }
        set { BackingStore.Set<string?>("comments_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("system_message_txt")]
    public string? SystemMessageTxt
    {
        get { return BackingStore.Get<string?>("system_message_txt"); }
        set { BackingStore.Set<string?>("system_message_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("latest_plea_cd")]
    public string? LatestPleaCd
    {
        get { return BackingStore.Get<string?>("latest_plea_cd"); }
        set { BackingStore.Set<string?>("latest_plea_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("latest_plea_update_dtm")]
    public DateTime? LatestPleaUpdateDtm
    {
        get { return BackingStore.GetDateTime("latest_plea_update_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("latest_plea_update_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }
}

/// <summary>
/// Represents a row in the tco_dispute_remarks table.
/// </summary>
public partial class TcoDisputeRemarks : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "tco_dispute_remarks";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("dispute_remark_id")]
    public long? DisputeRemarkId
    {
        get { return BackingStore.Get<long?>("dispute_remark_id"); }
        set { BackingStore.Set<long?>("dispute_remark_id", value, alwaysDirty: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_id")]
    public long? DisputeId
    {
        get { return BackingStore.Get<long?>("dispute_id"); }
        set { BackingStore.Set<long?>("dispute_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_remark_txt")]
    public string? DisputeRemarkTxt
    {
        get { return BackingStore.Get<string?>("dispute_remark_txt"); }
        set { BackingStore.Set<string?>("dispute_remark_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("full_user_name_txt")]
    public string? FullUserNameTxt
    {
        get { return BackingStore.Get<string?>("full_user_name_txt"); }
        set { BackingStore.Set<string?>("full_user_name_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("remarks_made_dtm")]
    public DateTime? RemarksMadeDtm
    {
        get { return BackingStore.GetDateTime("remarks_made_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("remarks_made_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }
}

/// <summary>
/// Represents a row in the tco_disputes table.
/// </summary>
public partial class TcoDisputes : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "tco_disputes";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("dispute_id")]
    public long? DisputeId
    {
        get { return BackingStore.Get<long?>("dispute_id"); }
        set { BackingStore.Set<long?>("dispute_id", value, alwaysDirty: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_status_type_cd")]
    public string? DisputeStatusTypeCd
    {
        get { return BackingStore.Get<string?>("dispute_status_type_cd"); }
        set { BackingStore.Set<string?>("dispute_status_type_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ticket_number_txt")]
    public string? TicketNumberTxt
    {
        get { return BackingStore.Get<string?>("ticket_number_txt"); }
        set { BackingStore.Set<string?>("ticket_number_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("officer_from_agen_id")]
    public decimal? OfficerFromAgenId
    {
        get { return BackingStore.Get<decimal?>("officer_from_agen_id"); }
        set { BackingStore.Set<decimal?>("officer_from_agen_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("to_be_heard_at_agen_id")]
    public decimal? ToBeHeardAtAgenId
    {
        get { return BackingStore.Get<decimal?>("to_be_heard_at_agen_id"); }
        set { BackingStore.Set<decimal?>("to_be_heard_at_agen_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("justin_rcc_id")]
    public decimal? JustinRccId
    {
        get { return BackingStore.Get<decimal?>("justin_rcc_id"); }
        set { BackingStore.Set<decimal?>("justin_rcc_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ticket_inbox_entry_id")]
    public long? TicketInboxEntryId
    {
        get { return BackingStore.Get<long?>("ticket_inbox_entry_id"); }
        set { BackingStore.Set<long?>("ticket_inbox_entry_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("occam_violation_ticket_upld_id")]
    public long? OccamViolationTicketUpldId
    {
        get { return BackingStore.Get<long?>("occam_violation_ticket_upld_id"); }
        set { BackingStore.Set<long?>("occam_violation_ticket_upld_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("occam_dispute_id")]
    public decimal? OccamDisputeId
    {
        get { return BackingStore.Get<decimal?>("occam_dispute_id"); }
        set { BackingStore.Set<decimal?>("occam_dispute_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("violation_dt")]
    public DateTime? ViolationDt
    {
        get { return BackingStore.GetDateTime("violation_dt", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("violation_dt", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("submitted_dt")]
    public DateTime? SubmittedDt
    {
        get { return BackingStore.GetDateTime("submitted_dt", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("submitted_dt", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("icbc_received_dt")]
    public DateTime? IcbcReceivedDt
    {
        get { return BackingStore.GetDateTime("icbc_received_dt", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("icbc_received_dt", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("vtc_assigned_to")]
    public string? VtcAssignedTo
    {
        get { return BackingStore.Get<string?>("vtc_assigned_to"); }
        set { BackingStore.Set<string?>("vtc_assigned_to", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("vtc_assigned_dtm")]
    public DateTime? VtcAssignedDtm
    {
        get { return BackingStore.GetDateTime("vtc_assigned_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("vtc_assigned_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("jj_assigned_to")]
    public string? JjAssignedTo
    {
        get { return BackingStore.Get<string?>("jj_assigned_to"); }
        set { BackingStore.Set<string?>("jj_assigned_to", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("jj_decision_dt")]
    public DateTime? JjDecisionDt
    {
        get { return BackingStore.GetDateTime("jj_decision_dt", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("jj_decision_dt", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("remarks_txt")]
    public string? RemarksTxt
    {
        get { return BackingStore.Get<string?>("remarks_txt"); }
        set { BackingStore.Set<string?>("remarks_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("hearing_type_cd")]
    public string? HearingTypeCd
    {
        get { return BackingStore.Get<string?>("hearing_type_cd"); }
        set { BackingStore.Set<string?>("hearing_type_cd", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("most_recent_decision_made_by")]
    public string? MostRecentDecisionMadeBy
    {
        get { return BackingStore.Get<string?>("most_recent_decision_made_by"); }
        set { BackingStore.Set<string?>("most_recent_decision_made_by", value); }
    }
}

/// <summary>
/// Represents a row in the tco_dispute_status_types table.
/// </summary>
public partial class TcoDisputeStatusTypes : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "tco_dispute_status_types";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("dispute_status_type_cd")]
    public string? DisputeStatusTypeCd
    {
        get { return BackingStore.Get<string?>("dispute_status_type_cd"); }
        set { BackingStore.Set<string?>("dispute_status_type_cd", value, alwaysDirty: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("dispute_status_type_dsc")]
    public string? DisputeStatusTypeDsc
    {
        get { return BackingStore.Get<string?>("dispute_status_type_dsc"); }
        set { BackingStore.Set<string?>("dispute_status_type_dsc", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("active_yn")]
    public string? ActiveYn
    {
        get { return BackingStore.Get<string?>("active_yn"); }
        set { BackingStore.Set<string?>("active_yn", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }
}

/// <summary>
/// Represents a row in the tco_error_logs table.
/// </summary>
public partial class TcoErrorLogs : DatabaseEntity
{
    [System.Text.Json.Serialization.JsonIgnore]
    public override string Name => "tco_error_logs";

    /// <summary>
    /// Primary Key
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("error_log_id")]
    public long? ErrorLogId
    {
        get { return BackingStore.Get<long?>("error_log_id"); }
        set { BackingStore.Set<long?>("error_log_id", value, alwaysDirty: true); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("error_message_no")]
    public long? ErrorMessageNo
    {
        get { return BackingStore.Get<long?>("error_message_no"); }
        set { BackingStore.Set<long?>("error_message_no", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("error_message_txt")]
    public string? ErrorMessageTxt
    {
        get { return BackingStore.Get<string?>("error_message_txt"); }
        set { BackingStore.Set<string?>("error_message_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("program_nm")]
    public string? ProgramNm
    {
        get { return BackingStore.Get<string?>("program_nm"); }
        set { BackingStore.Set<string?>("program_nm", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("program_version_txt")]
    public string? ProgramVersionTxt
    {
        get { return BackingStore.Get<string?>("program_version_txt"); }
        set { BackingStore.Set<string?>("program_version_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("error_detail_txt")]
    public string? ErrorDetailTxt
    {
        get { return BackingStore.Get<string?>("error_detail_txt"); }
        set { BackingStore.Set<string?>("error_detail_txt", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_dtm")]
    public DateTime? EntDtm
    {
        get { return BackingStore.GetDateTime("ent_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("ent_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("ent_user_id")]
    public string? EntUserId
    {
        get { return BackingStore.Get<string?>("ent_user_id"); }
        set { BackingStore.Set<string?>("ent_user_id", value); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_dtm")]
    public DateTime? UpdDtm
    {
        get { return BackingStore.GetDateTime("upd_dtm", format: "yyyy-MM-dd HH:mm:ss"); }
        set { BackingStore.SetDateTime("upd_dtm", value, format: "yyyy-MM-dd HH:mm:ss"); }
    }

    [System.Text.Json.Serialization.JsonPropertyName("upd_user_id")]
    public string? UpdUserId
    {
        get { return BackingStore.Get<string?>("upd_user_id"); }
        set { BackingStore.Set<string?>("upd_user_id", value); }
    }
}

